### ISSUE TITLE
readthedocs build fails due to pycurl

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1390]
Motivation
----------
Currently the build process on readthedocs fails.

```
Collecting pycurl>=7.19 (from fts3-rest-API==3.7.1->-r requirements.readthedocs.txt (line 44))
  Using cached https://files.pythonhosted.org/packages/e8/e4/0dbb8735407189f00b33d84122b9be52c790c7c3b25286826f4e1bdb7bde/pycurl-7.43.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jSh8ZH/pycurl/setup.py", line 913, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-build-jSh8ZH/pycurl/setup.py", line 582, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-build-jSh8ZH/pycurl/setup.py", line 99, in __init__
        self.configure()
      File "/tmp/pip-build-jSh8ZH/pycurl/setup.py", line 227, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jSh8ZH/pycurl/
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by bari12** [comment]
Still does not work: https://readthedocs.org/projects/rucio/builds/7547086/

**Comment by bari12** [comment]
So this probably needs to wait until pycurl is an extra in the fts3-rest-api package. For now, although only the requirements.readthedocs.txt should be used, it seems like rucio as a package is pulled in as well, which then requires pycurl via fts3-rest-api, crashing readthedocs build.
Needs a version > 3.7.1 https://pypi.org/project/fts3-rest-API/#history
