### ISSUE TITLE
Define stricter depdency ranges for pip-requires-client

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1692]
Motivation
----------
There was an update of urllib3 to 1.24 which is incompatible with requests 2.19.1. However, requests specifies that it needs urllib<1.24, thus this should be considered by pip when installing the dependencies of Rucio. For some reason it is not:

```
> rucio
/tmp/rucio_test_install/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/tmp/rucio_test_install/bin/rucio", line 57, in <module>
    from rucio.client.client import Client
  File "/tmp/rucio_test_install/lib/python2.7/site-packages/rucio/client/__init__.py", line 19, in <module>
    from rucio.client.client import *  # NOQA pylint: disable=wildcard-import
  File "/tmp/rucio_test_install/lib/python2.7/site-packages/rucio/client/client.py", line 27, in <module>
    from rucio.client.accountclient import AccountClient
  File "/tmp/rucio_test_install/lib/python2.7/site-packages/rucio/client/accountclient.py", line 27, in <module>
    from requests.status_codes import codes
  File "/tmp/rucio_test_install/lib/python2.7/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/tmp/rucio_test_install/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/tmp/rucio_test_install/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/tmp/rucio_test_install/lib/python2.7/site-packages/requests/compat.py", line 48, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```

**Comment by bari12** [comment]
So the issue here is that the pip dependency resolver is not all that good https://github.com/pypa/pip/issues/988
We need to define stricter dependency ranges for this.
