### ISSUE TITLE
Hermes critical errors

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1702]
Motivation
----------
Traceback :
```
2018-10-25 12:43:03,955 21738   CRITICAL        Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/hermes/hermes.py", line 259, in deliver_messages
    conn.connect(wait=True)
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 215, in connect
    Protocol12.connect(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/stomp/protocol.py", line 504, in connect
    headers[HDR_HOST] = self.transport.current_host_and_port[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by mlassnig** [comment]
Not a bug. This is CERN Megabus force overwriting the Rucio stomp.py dependency.
