### ISSUE TITLE
bb8 is failing with division by 0

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#1792]
Motivation
----------
when calculating the ratio of secondaries and total:
https://github.com/rucio/rucio/blob/master/lib/rucio/daemons/bb8/t2_background_rebalance.py#L40
the bb8 is sometimes attempting dividing by zero.

Modification
------------
exclude such a cases.

**Comment by TomasJavurek** [comment]
Traceback (most recent call last):
 File "/opt/rucio/lib/rucio/daemons/bb8/t2_background_rebalance.py", line 111, in <module>
   rebalance_rse(source_rse['rse'], max_bytes=available_target_rebalance_volume, dry_run=False, comment='T2 Background rebalancing', force_expression=destination_rse['rse'])
 File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 351, in new_funct
   result = function(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/rucio/daemons/bb8/common.py", line 339, in rebalance_rse
   for scope, name, rule_id, rse_expression, subscription_id, bytes, length in list_rebalance_rule_candidates(rse=rse, mode=mode):
 File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 360, in new_funct
   raise DatabaseException(str(error))
rucio.common.exception.DatabaseException: Database exception.
Details: (cx_Oracle.DatabaseError) ORA-01476: divisor is equal to zero
[SQL: u"SELECT dsl.scope as scope, dsl.name as name, rawtohex(r.id) as rule_id, r.rse_expression as rse_expression, r.subscription_id as subscription_id, d.bytes as bytes, d.length as length FROM atlas_rucio.dataset_locks dsl JOIN atlas_rucio.rules r ON (dsl.rule_id = r.id) JOIN atlas_rucio.dids d ON (dsl.scope = d.scope and dsl.name = d.name)\nWHERE\ndsl.rse_id = atlas_rucio.rse2id(:rse) and\n(r.expires_at > sysdate+60 or r.expires_at is NULL) and\nr.created_at < sysdate-60 and\nr.account IN ('panda', 'root', 'ddmadmin') and\nr.state = 'O' and\nr.copies = 1 and\nr.did_type = 'D' and\nr.child_rule_id is NULL and\nd.bytes is not NULL and\nd.bytes/d.length > 500*1000*1000 and\nd.is_open = 0 and\nd.did_type = 'D' and\nr.grouping IN ('D', 'A') and\n1 = (SELECT count(*) FROM atlas_rucio.dataset_locks WHERE scope=dsl.scope and name=dsl.name and rse_id = dsl.rse_id)\nORDER BY dsl.accessed_at ASC NULLS FIRST, d.bytes DESC"] [parameters: {u'rse': u'OU_OSCER_ATLAS_DATADISK'}] (Background on this error at: http://sqlalche.me/e/4xp6)

**Comment by TomasJavurek** [comment]
The original problem was, that I set manually the limit on fsize, calculated as bytes/length. This was done only localy at prod-02. I removed that and rather ordered the query by fsize. There is no division by 0 anymore.
