### ISSUE TITLE
import of builtins not Python 2.6 compatible in downloadclient

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1845]
Motivation
----------
https://github.com/rucio/rucio/blob/06e4f7e3ac03111f1ec94add1be3524d3d0fc4d9/lib/rucio/client/downloadclient.py#L35 is not compatible to Python 2.6 it seems, which is a problem for the deployment on the grid

Py2.6:
```
[desilva@atlas-sl6x64 ~]$ rucio --version
Traceback (most recent call last):
  File "/ALRB/atlasadmin/atlas-sl6x64.triumf.ca/ATLASLocalRootBase/x86_64/rucio-clients/1.18.6/bin/rucio", line 63, in <module>
    from rucio.client.downloadclient import DownloadClient
  File "/ALRB/atlasadmin/atlas-sl6x64.triumf.ca/ATLASLocalRootBase/x86_64/rucio-clients/1.18.6/lib/python2.7/site-packages/rucio/client/downloadclient.py", line 35, in <module>
    from builtins import round
ImportError: No module named builtins
```

**Comment by bari12** [comment]
Not sure why this was not caught by the Python 2.6 test though?

**Comment by hahahannes** [comment]
I will remove the imports and add a basic test to the python2.6 client test to check at least imports. Also the pylint check for python3 has to be changed to ignore round errors.
