### ISSUE TITLE
authentication type selection safeguard

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#2006]
Motivation
----------

Selection of the authentication type should be case-sensitive and not throw an error.

```
(rucio-env) [rjoshi@rucio-bastion ~]$ rucio -a rjoshi -S X509  -v whoami

2019-01-20 09:43:15,381 ERROR Cannot authenticate.

Details: auth type 'X509' not supported

2019-01-20 09:43:15,382 DEBUG Traceback (most recent call last):

  File "/opt/rucio-env/bin/rucio", line 160, in new_funct

    return function(*args, **kwargs)

  File "/opt/rucio-env/bin/rucio", line 300, in whoami_account

    client = get_client(args)

  File "/opt/rucio-env/bin/rucio", line 273, in get_client

    elif auth_type == 'x509_proxy':

UnboundLocalError: local variable 'auth_type' referenced before assignment



2019-01-20 09:43:15,383 ERROR local variable 'auth_type' referenced before assignment

2019-01-20 09:43:15,383 ERROR

Rucio exited with an unexpected/unknown error.

Please rerun the last command with the "-v" option to gather more information.

If it's a problem concerning your experiment or if you're unsure what to do, please followup at: alastair.dewhurst@cern.ch

If you're sure there is a problem with Rucio itself, please followup at: https://github.com/rucio/rucio/issues/

Completed in 0.0026 sec.
```

**Comment by mlassnig** [comment]
One more, seems like the exception handler is borked (x509 is lowercase now, but cert does not exist)


```
rucio-env) [rjoshi@rucio-bastion ~]$ rucio -v -a rjoshi -S x509 whoami

given client cert (/opt/rucio/etc/web/client.crt) doesn't exist

2019-01-21 09:53:37,149	ERROR	Cannot authenticate.

Details: x509 authentication failed

2019-01-21 09:53:37,150	DEBUG	Traceback (most recent call last):

  File "/opt/rucio-env/bin/rucio", line 160, in new_funct

    return function(*args, **kwargs)

  File "/opt/rucio-env/bin/rucio", line 300, in whoami_account

    client = get_client(args)

  File "/opt/rucio-env/bin/rucio", line 273, in get_client

    elif auth_type == 'x509_proxy':

UnboundLocalError: local variable 'auth_type' referenced before assignment



2019-01-21 09:53:37,151	ERROR	local variable 'auth_type' referenced before assignment

2019-01-21 09:53:37,151	ERROR	

Rucio exited with an unexpected/unknown error.

Please rerun the last command with the "-v" option to gather more information.

If it's a problem concerning your experiment or if you're unsure what to do, please followup at: alastair.dewhurst@cern.ch

If you're sure there is a problem with Rucio itself, please followup at: https://github.com/rucio/rucio/issues/

Completed in 0.0028 sec.
```
