### ISSUE TITLE
Error when adding dataset with lifetime

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#244]
Motivation
----------

```
$ rucio -v add-dataset user.briedel:test_test_test --lifetime 100
2017-11-30 16:01:50,357 ERROR [No JSON object could be decoded]
2017-11-30 16:01:50,357 ERROR [Rucio exited with an unexpected/unknown error. Please rerun the last command with the '-v' option and submit a ticket with all the necessary information at https://its.cern.ch/jira/browse/RUCIO]
2017-11-30 16:01:50,359 DEBUG [Traceback (most recent call last):
  File "/usr/bin/rucio", line 161, in new_funct
    return function(*args, **kwargs)
  File "/usr/bin/rucio", line 423, in add_dataset
    client.add_dataset(scope=scope, name=name, statuses={'monotonic': args.monotonic}, lifetime=args.lifetime)
  File "/usr/lib/python2.7/site-packages/rucio/client/didclient.py", line 131, in add_dataset
    lifetime=lifetime, dids=files, rse=rse)
  File "/usr/lib/python2.7/site-packages/rucio/client/didclient.py", line 100, in add_did
    exc_cls, exc_msg = self._get_exception(headers=r.headers, status_code=r.status_code, data=r.content)
  File "/usr/lib/python2.7/site-packages/rucio/client/baseclient.py", line 191, in _get_exception
    data = parse_response(data)
  File "/usr/lib/python2.7/site-packages/rucio/common/utils.py", line 193, in parse_response
    return json.loads(data, object_hook=datetime_parser)
  File "/usr/lib64/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
]
Completed in 0.0916 sec.
```

**Comment by bari12** [comment]
What's the exact command you did?

**Comment by vingar** [comment]
it's there but hidden in the code formatting:

rucio -v add-dataset user.briedel:test_test_test --lifetime 100
