### ISSUE TITLE
SITE1_DISK error in demo docker installation 

### ISSUE THREAD

**Issue by purusharths** [rucio/rucio#2771]
Motivation
----------
The following error occurs in the docker container for setting up rucio demo upon running `setup.py` (PS: The docker container was created as instructed [here](https://rucio.readthedocs.io/en/latest/installing_demo.html))

```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 2cbee484dcf9
RSE does not exist.
Details: RSE 'SITE1_DISK' cannot be found
(exceptions.ValueError) badly formed hexadecimal UUID string
[SQL: SELECT rses.rse AS rses_rse 
FROM rses 
WHERE rses.id = ? AND rses.deleted = 0]
[parameters: [{}]]
Traceback (most recent call last):
  File "./setup_data.py", line 54, in <module>
    add_protocol('SITE1_DISK', params)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 356, in new_funct
    result = function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/rse.py", line 785, in add_protocol
    rse = get_rse_name(rse_id=rse_id, session=session, include_deleted=False)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 288, in new_funct
    return function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/rse.py", line 282, in get_rse_name
    result = query.one()[0]
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3275, in one
    ret = self.one_or_none()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
    ret = list(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 719, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 1201, in process
    return process_param(value, dialect)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/types.py", line 57, in process_bind_param
    return "%.32x" % uuid.UUID(value)
  File "/usr/lib64/python2.7/uuid.py", line 134, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
sqlalchemy.exc.StatementError: (exceptions.ValueError) badly formed hexadecimal UUID string
[SQL: SELECT rses.rse AS rses_rse 
FROM rses 
WHERE rses.id = ? AND rses.deleted = 0]
[parameters: [{}]]
```
Apparently, when the `SITE1_DISK` folder is not created, then in `/usr/lib/python2.7/site-packages/rucio/db/sqla/types.py` 
```
 56             if not isinstance(value, uuid.UUID):
 57                 return "%.32x" % uuid.UUID(value)
```
the variable `value` is the string "SITE1_DISK" which throws the error. However, if I run `setup.py` again, the string in `value` is changed to `db851d85729f495e84286e7a08fa5f23` but now it falls prey to `sqlalchemy.exc.IntegrityError`.
```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) columns account, rse_id are not unique
[SQL: INSERT INTO account_usage (account, rse_id, files, bytes, updated_at, created_at) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('root', 'db851d85729f495e84286e7a08fa5f23', 0, 0, '2019-08-01 06:15:22.608647', '2019-08-01 06:15:22.608657')]
(Background on this error at: http://sqlalche.me/e/gkpj)
``` 
Any suggestions around this?

**Comment by ijjorama** [comment]
I would like to see a fix for this as well. I checked out the latest Rucio source this morning and found the bug with the /setup_demo.sh script to still be present.

**Comment by bari12** [comment]
We are moving away from the `demo` containers in favor of the `dev` containers which are much more advanced. @mlassnig is the error above an issue for the dev ones? I don't think so, as it uses root containers for storage emulation?

**Comment by mlassnig** [comment]
demo needs to be removed, it's unmaintained. see here: https://github.com/rucio/rucio/pull/2936

**Comment by bari12** [comment]
Demo has been removed;
