### ISSUE TITLE
Undertaker can not delete did with Generic Metadata

### ISSUE THREAD

**Issue by arisfkiaras** [rucio/rucio#2840]
Motivation
----------
Doing 
```
$ rucio add-dataset testing:test_under2
$ rucio add-did-meta --did testing:test_under2 --key MYKEY --value MYVALUE
$ rucio erase testing:test_under2
```
Gives me the following error on undertaker 1.20.3
```
(psycopg2.errors.ForeignKeyViolation) update or delete on table "dids" violates foreign key constraint "DID_META_FK" on table "did_meta"
DETAIL:  Key (scope, name)=(testing, test_under2) is still referenced from table "did_meta".

[SQL: DELETE FROM dids WHERE dids.scope = %(scope_1)s AND dids.name = %(name_1)s AND (dids.did_type = %(did_type_1)s OR dids.did_type = %(did_type_2)s)]
[parameters: {'name_1': 'test_under2', 'did_type_1': 'C', 'scope_1': 'testing', 'did_type_2': 'D'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-08-16 15:31:02,264	7	CRITICAL	Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/undertaker/undertaker.py", line 109, in undertaker
    logging.error('Undertaker(%s): Got database error %s.', worker_number, str(error))
UnboundLocalError: local variable 'error' referenced before assignment

2019-08-16 15:31:03,276	7	INFO	Undertaker(1/1): Live gives {'nr_threads': 1, 'assign_thread': 0}
2019-08-16 15:31:03,282	7	INFO	Undertaker(1): Receive 1 dids to delete
2019-08-16 15:31:03,282	7	INFO	Removing did testing:test_under2 (DATASET)
(psycopg2.errors.ForeignKeyViolation) update or delete on table "dids" violates foreign key constraint "DID_META_FK" on table "did_meta"
DETAIL:  Key (scope, name)=(testing, test_under2) is still referenced from table "did_meta".

[SQL: DELETE FROM dids WHERE dids.scope = %(scope_1)s AND dids.name = %(name_1)s AND (dids.did_type = %(did_type_1)s OR dids.did_type = %(did_type_2)s)]
[parameters: {'name_1': 'test_under2', 'did_type_1': 'C', 'scope_1': 'testing', 'did_type_2': 'D'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-08-16 15:31:03,298	7	CRITICAL	Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/undertaker/undertaker.py", line 109, in undertaker
    logging.error('Undertaker(%s): Got database error %s.', worker_number, str(error))
UnboundLocalError: local variable 'error' referenced before assignment

```
Having a look at the code I believe the UnboundLocalError has been already fixed for the next releases.
The Foreign key constraint seems to be there.

Modification
------------
Delete metadata for did which is about to be deleted?

I wouldn't mind having a look and doing a pr

**Comment by bari12** [comment]
Hi @arisfkiaras 
Yes, please have a look! Thanks 😄

**Comment by arisfkiaras** [comment]
Interesting enough the ```rucio add-did-meta``` seems not to be working at all on the rucio dev container.
Even though the alembic version is the same as my production server (2cbee484dcf9) on the rucio dev db the table did_meta does not include the 'updated_at' and 'created_at' columns while on my production db it does.

**Comment by hahahannes** [comment]
Yes, I also noticed that and already opened #2462. But couldnt find a fix so far

**Comment by arisfkiaras** [comment]
Thanks Hannes, I had not seen that issue.

Another interesting finding, test_did_meta.py seem to succeed for any RucioException.
https://github.com/rucio/rucio/blob/master/lib/rucio/tests/test_did_meta.py#L55

I guess we can discuss this tomorrow in the meeting in conjunction with some generic metadata query times.
