### ISSUE TITLE
Background rebalacing error due to multi-VO support

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#2895]
```
Traceback (most recent call last):
  File "/opt/rucio/lib/rucio/daemons/bb8/nuclei_background_rebalance.py", line 141, in <module>
    rebalance_rse(source_rse['rse'], max_bytes=available_target_rebalance_volume, dry_run=False, comment='Nuclei Background rebalancing', force_expression=destination_rse['rse'])
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 356, in new_funct
    result = function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/daemons/bb8/common.py", line 370, in rebalance_rse
    for scope, name, rule_id, rse_expression, subscription_id, bytes, length, fsize in list_rebalance_rule_candidates(rse=rse, mode=mode):
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 356, in new_funct
    result = function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/daemons/bb8/common.py", line 280, in list_rebalance_rule_candidates
    models.DatasetLock.accessed_at).all()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3161, in all
    return list(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 745, in _init_compiled
    for key in compiled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 745, in <genexpr>
    for key in compiled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 1196, in process
    return impl_processor(process_param(value, dialect))
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/types.py", line 160, in process_bind_param
    raise InvalidType('Cannot insert to db. Expected InternalAccount, got string type.')
sqlalchemy.exc.StatementError: (rucio.common.exception.InvalidType) Provided type is considered invalid.
Details: Cannot insert to db. Expected InternalAccount, got string type.
[SQL: SELECT atlas_rucio.dataset_locks.scope AS atlas_rucio_dataset_lock_1, atlas_rucio.dataset_locks.name AS atlas_rucio_dataset_lock_2, atlas_rucio.rules.id AS atlas_rucio_rules_id, atlas_rucio.rules.rse_expression AS atlas_rucio_rules_rse_ex_3, atlas_rucio.rules.subscription_id AS atlas_rucio_rules_subscr_4, atlas_rucio.dids.bytes AS atlas_rucio_dids_bytes, atlas_rucio.dids.length AS atlas_rucio_dids_length, CASE WHEN (atlas_rucio.dataset_locks.length < :length_1 OR atlas_rucio.dataset_locks.length IS NULL) THEN :param_1 ELSE CAST(atlas_rucio.dataset_locks.bytes / atlas_rucio.dataset_locks.length AS INTEGER) END AS anon_1
FROM atlas_rucio.dataset_locks JOIN atlas_rucio.rules ON atlas_rucio.rules.id = atlas_rucio.dataset_locks.rule_id JOIN atlas_rucio.dids ON atlas_rucio.dataset_locks.scope = atlas_rucio.dids.scope AND atlas_rucio.dataset_locks.name = atlas_rucio.dids.name
WHERE atlas_rucio.dataset_locks.rse_id = :rse_id_1 AND (atlas_rucio.rules.expires_at > :expires_at_1 OR atlas_rucio.rules.expires_at IS NULL) AND atlas_rucio.rules.created_at < :created_at_1 AND atlas_rucio.rules.account IN (:account_1, :account_2, :account_3) AND atlas_rucio.rules.state = :state_1 AND atlas_rucio.rules.did_type = :did_type_1 AND atlas_rucio.rules.copies = :copies_1 AND atlas_rucio.rules.child_rule_id IS NULL AND atlas_rucio.rules.grouping IN (:grouping_1, :grouping_2) AND atlas_rucio.dids.bytes IS NOT NULL AND atlas_rucio.dids.is_open = :is_open_1 AND atlas_rucio.dids.did_type = :did_type_2 AND CASE WHEN (atlas_rucio.dataset_locks.length < :length_2 OR atlas_rucio.dataset_locks.length IS NULL) THEN :param_2 ELSE CAST(atlas_rucio.dataset_locks.bytes / atlas_rucio.dataset_locks.length AS INTEGER) END > :param_3 AND (SELECT count(*) AS count_1
FROM atlas_rucio.dataset_locks dataset_locks_1
WHERE dataset_locks_1.scope = atlas_rucio.dataset_locks.scope AND dataset_locks_1.name = atlas_rucio.dataset_locks.name AND dataset_locks_1.rse_id = atlas_rucio.dataset_locks.rse_id) = :param_4 ORDER BY CASE WHEN (atlas_rucio.dataset_locks.length < :length_3 OR atlas_rucio.dataset_locks.length IS NULL) THEN :param_5 ELSE CAST(atlas_rucio.dataset_locks.bytes / atlas_rucio.dataset_locks.length AS INTEGER) END, atlas_rucio.dataset_locks.accessed_at]
[parameters: [{}]]
```

**Comment by bari12** [comment]
In the rebalancing script we need to update scopes/account strings to InternalScope/InternalAccount. This should be not too difficult to fix. @dchristidis can you maybe have a look since @TomasJavurek is not available at the moment? Thanks!
