### ISSUE TITLE
Problem handling unicode characters

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2915]
Motivation
----------

Traceback :
```
[Thu Sep 19 08:30:41.397728 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832] Traceback (most recent call last):
[Thu Sep 19 08:30:41.397762 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]   File "/usr/lib/python2.7/site-packages/web/application.py", line 239, in process
[Thu Sep 19 08:30:41.397766 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]     return self.handle()
[Thu Sep 19 08:30:41.397774 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]   File "/usr/lib/python2.7/site-packages/web/application.py", line 230, in handle
[Thu Sep 19 08:30:41.397777 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]     return self._delegate(fn, self.fvars, args)
[Thu Sep 19 08:30:41.397780 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]   File "/usr/lib/python2.7/site-packages/web/application.py", line 462, in _delegate
[Thu Sep 19 08:30:41.397783 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]     return handle_class(cls)
[Thu Sep 19 08:30:41.397786 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]   File "/usr/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
[Thu Sep 19 08:30:41.397789 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]     return tocall(*args)
[Thu Sep 19 08:30:41.397791 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]   File "/usr/lib/python2.7/site-packages/rucio/web/rest/account.py", line 509, in POST
[Thu Sep 19 08:30:41.397794 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]     raise generate_http_error(409, 'Duplicate', error.args[0])
[Thu Sep 19 08:30:41.397797 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]   File "/usr/lib/python2.7/site-packages/rucio/common/utils.py", line 309, in generate_http_error
[Thu Sep 19 08:30:41.397800 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]     if len(str(exc_msg)) > 15000:
[Thu Sep 19 08:30:41.397803 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832] UnicodeEncodeError: 'ascii' codec can't encode character u'\\xed' in position 89: ordinal not in range(128)
[Thu Sep 19 08:30:41.397823 2019] [:error] [pid 3042:tid 139805664990976] [client 188.185.80.147:50832]
```

**Comment by bziemons** [comment]
@bari12 as I said, this should only happen with Python 2 as in Python 3 all strings are unicode capable by default. Should I still fix it?
