### ISSUE TITLE
Fixed badly merged conf.py file 

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#307]

**Comment by vingar** [comment]
Motivation
-----------

Badly merged conf.py file makes sphinx failing:

Running Sphinx v1.6.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/rucio-blueprint/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/rucio-blueprint/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/rucio-blueprint/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 152, in __init__
    raise ConfigError(CONFIG_SYNTAX_ERROR % err)
ConfigError: There is a syntax error in your configuration file: invalid syntax (conf.py, line 51)

Configuration error:
There is a syntax error in your configuration file: invalid syntax (conf.py, line 51)

**Comment by bari12** [comment]
This is a duplicate of #255

**Comment by vingar** [comment]
closed
