### ISSUE TITLE
Improvements to the declaration of lost files

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#3235]
I would like to make the following suggestions:

 1. Use the synchronous API in case the number of files is below some thresholds. We had a case where a request to mark a large amount of files as temporarily unavailable was causing long delays for single-file requests which should have had higher priority.
 2. Change the message to something other than `replicas successfully declared`. This is misleading as the PFNs could be invalid and the user will move on thinking that everything is done.
 3. Do some checking on the PFNs, at the very least that they are valid URLs. It should be noted that on the side of Minos this isn’t handled gracefully.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/badreplicas/minos.py", li
ne 182, in minos
    dict_rse[rse_id].extend(tmp_dict_rse[rse_id])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 284, in
 new_funct
    return function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/replica.py", line 437, in ge
t_pfn_to_rse
    split_se = surl.split('/')[2].split(':')
```

**Comment by cserf** [comment]
Needs https://github.com/rucio/rucio/issues/4411 for 3.
