### ISSUE TITLE
Update of MultiHop requests

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#3451]
Motivation
----------
On the ATLAS deployment we see the following error.
```
2020-04-07 10:49:54,079 17260   CRITICAL        Thread [7/31] :  Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/conveyor/submitter.py", line 170, in submitter
    retry_other_fts=retry_other_fts)
  File "/usr/lib/python2.7/site-packages/rucio/daemons/conveyor/submitter.py", line 324, in __get_transfers
    request_core.set_requests_state(reqs_no_source, RequestState.NO_SOURCES)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 365, in new_funct
    result = function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/request.py", line 526, in set_requests_state
    set_request_state(request_id, new_state, session=session)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 381, in new_funct
    result = function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/request.py", line 509, in set_request_state
    raise UnsupportedOperation("Request %s state cannot be updated." % request_id)
UnsupportedOperation: The resource doesn't support the requested operation.
Details: Request ff80322c22044da9b53b489a95b717e3 state cannot be updated.
```
Needs to be investigated.

**Comment by bari12** [comment]
This might be a duplicate of #4511 
@rcarpa can you please check.
