### ISSUE TITLE
rucio client container missing things

### ISSUE THREAD

**Issue by ivukotic** [rucio/rucio#3511]
I tried to use the latest docker image and it does not work:

rucio whoami
Traceback (most recent call last):
  File "/usr/bin/rucio", line 64, in <module>
    from rucio.client.uploadclient import UploadClient
  File "/usr/lib/python2.7/site-packages/rucio/client/uploadclient.py", line 41, in <module>
    from rucio.rse import rsemanager as rsemgr
  File "/usr/lib/python2.7/site-packages/rucio/rse/__init__.py", line 94, in <module>
    from rucio.core.rse import get_rse_protocols, get_rse_id
ImportError: No module named core.rse

**Comment by bari12** [comment]
Hi Ilija,
I think this is linked to your rucio.cfg which includes a `[database]` section. When this is there the API thinks it is running on a server and will use internal functions to resolve certain things, which will not work in a pure client container.

**Comment by ivukotic** [comment]
Hi,
well, I am not creating rucio.cfg. It should be done for me. If you look at .bashrc you will find:
`if [ ! -f /opt/rucio/etc/rucio.cfg ]; then
    echo "File rucio.cfg not found. It will generate one."
    mkdir -p /opt/rucio/etc/
    j2 rucio.cfg.j2 > /opt/rucio/etc/rucio.cfg
fi`

that has an issue that it has path wrong. It should be /rucio.cfg.j2

If I fix that manually, I get this:
`[client]
rucio_host = localhost
auth_host = localhost
ca_cert = /etc/pki/tls/certs/ca-bundle.crt
auth_type =
username =
password =
account =
client_cert =
client_key =
client_x509_proxy =
request_retries = 3

[policy]
permission = generic
schema = generic
lfn2pfn_algorithm_default = hash
support = https://github.com/rucio/rucio/issues/
support_rucio = https://github.com/rucio/rucio/issues/`

As you can see this has no [database] section.

**Comment by bari12** [comment]
Yes, that seems to be the issue. Without the rucio.cfg it also seems to assume server mode. @tbeerman
