### ISSUE TITLE
rucio-admin scope list --account traceback

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#3561]
Motivation
----------
```
$ rucio-admin scope list --account ldmx-user
Scope does not exist.
Details: no scopes found for account ID 'ldmx-user'
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/home/centos/act/bin/rucio-admin", line 130, in new_funct
    return function(*args, **kwargs)
  File "/home/centos/act/bin/rucio-admin", line 737, in list_scopes
    scopes = client.list_scopes_for_account(args.account)
  File "/home/centos/act/lib64/python3.6/site-packages/rucio/client/scopeclient.py", line 104, in list_scopes_for_account
    raise exc_cls(exc_msg)
rucio.common.exception.ScopeNotFound: Scope does not exist.
Details: no scopes found for account ID 'ldmx-user'
```

Modification
------------

Just the error message should be printed without the traceback.

**Comment by bari12** [comment]
Hi @davidgcameron, just for my information, will you submit a PR for the two issues you posted?

**Comment by davidgcameron** [comment]
No, I wasn't planning to fix them, just reporting for the record :) Neither of the issues are critical or blocking.
