### ISSUE TITLE
Adding distance fails wiht 500 if already exists

### ISSUE THREAD

**Issue by vokac** [rucio/rucio#3767]
When distance is added (accidentally) for second time, Rucio responds with 500 Internal server error instead of some reasonable error:

```shell
$ rucio-admin rse add-distance --distance 1 --ranking 1 WLCG_CERN-EOS_H WLCG_INFN-T1-STO_H
$ rucio-admin rse add-distance --distance 1 --ranking 1 WLCG_CERN-EOS_H WLCG_INFN-T1-STO_H
An unknown exception occurred.
Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97'))
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/home/vokac/dpm/tpc/rucio-doma/rucio/bin/rucio-admin", line 132, in new_funct
    return function(*args, **kwargs)
  File "/home/vokac/dpm/tpc/rucio-doma/rucio/bin/rucio-admin", line 625, in add_distance_rses
    client.add_distance(args.source, args.destination, params)
  File "/home/vokac/dpm/tpc/rucio-doma/rucio/lib/python2.7/site-packages/rucio/client/rseclient.py", line 542, in add_distance
    raise exc_cls(exc_msg)
RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97'))
```

**Comment by bari12** [comment]
Probably due to Duplicate Entry
