### ISSUE TITLE
Listing account usage: internal server error

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#3768]
Motivation
----------

```
$ rucio list-account-usage --rse DESY-HH_LOCALGROUPDISK dsouth
+------------------------+-----------+-----------+--------------+
| RSE                    | USAGE     | LIMIT     | QUOTA LEFT   |
|------------------------+-----------+-----------+--------------|
| DESY-HH_LOCALGROUPDISK | 44.245 MB | 10.000 TB | 10.000 TB    |
+------------------------+-----------+-----------+--------------+
2020-06-24 15:19:26,807 ERROR   An unknown exception occurred.
Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97'))
```

```
[Wed Jun 24 15:24:46.816844 2020] [:error] [pid 8341:tid 140073777170176] Traceback (most recent call last):
[Wed Jun 24 15:24:46.816918 2020] [:error] [pid 8341:tid 140073777170176]   File "/usr/lib/python2.7/site-packages/rucio/web/rest/account.py", line 776, in GET
[Wed Jun 24 15:24:46.816926 2020] [:error] [pid 8341:tid 140073777170176]     for usage in get_global_account_usage(account=account, rse_expression=rse_expression, issuer=ctx.env.get('issuer')):
[Wed Jun 24 15:24:46.816933 2020] [:error] [pid 8341:tid 140073777170176]   File "/usr/lib/python2.7/site-packages/rucio/api/account_limit.py", line 237, in get_global_account_usage
[Wed Jun 24 15:24:46.816936 2020] [:error] [pid 8341:tid 140073777170176]     if not rucio.api.permission.has_permission(issuer=issuer, action='get_global_account_usage', kwargs=kwargs):
[Wed Jun 24 15:24:46.816962 2020] [:error] [pid 8341:tid 140073777170176]   File "/usr/lib/python2.7/site-packages/rucio/api/permission.py", line 65, in has_permission
[Wed Jun 24 15:24:46.816966 2020] [:error] [pid 8341:tid 140073777170176]     return permission.has_permission(issuer=issuer, action=action, kwargs=kwargs)
[Wed Jun 24 15:24:46.816971 2020] [:error] [pid 8341:tid 140073777170176]   File "/usr/lib/python2.7/site-packages/rucio/core/permission/atlas.py", line 123, in has_permission
[Wed Jun 24 15:24:46.816974 2020] [:error] [pid 8341:tid 140073777170176]     return perm.get(action, perm_default)(issuer=issuer, kwargs=kwargs)
[Wed Jun 24 15:24:46.816977 2020] [:error] [pid 8341:tid 140073777170176]   File "/usr/lib/python2.7/site-packages/rucio/core/permission/generic.py", line 869, in perm_get_global_account_usage
[Wed Jun 24 15:24:46.817036 2020] [:error] [pid 8341:tid 140073777170176]     for rse in parse_expression(kwargs['rse_expression'])}
[Wed Jun 24 15:24:46.817043 2020] [:error] [pid 8341:tid 140073777170176]   File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 365, in new_funct
[Wed Jun 24 15:24:46.817046 2020] [:error] [pid 8341:tid 140073777170176]     result = function(*args, **kwargs)
[Wed Jun 24 15:24:46.817048 2020] [:error] [pid 8341:tid 140073777170176]   File "/usr/lib/python2.7/site-packages/rucio/core/rse_expression_parser.py", line 66, in parse_expression
[Wed Jun 24 15:24:46.817051 2020] [:error] [pid 8341:tid 140073777170176]     result = REGION.get(sha256(expression.encode()).hexdigest())
[Wed Jun 24 15:24:46.817061 2020] [:error] [pid 8341:tid 140073777170176] AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by bziemons** [comment]
Already fixed in 0e3b54bce060883031ba34810b9aa05a11a0e401 (https://github.com/rucio/rucio/pull/3875)
