### ISSUE TITLE
kronos stuck after database downtime

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#3776]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/daemons/tracer/kronos.py", line 350, in kronos_file
    live(executable=executable, hostname=hostname, pid=pid, thread=thread)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 374, in new_funct
    raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (cx_Oracle.DatabaseError) ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
(Background on this error at: http://sqlalche.me/e/4xp6)

(cx_Oracle.DatabaseError) ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
(Background on this error at: http://sqlalche.me/e/4xp6)
(cx_Oracle.DatabaseError) ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
(Background on this error at: http://sqlalche.me/e/4xp6)
2020-06-27 14:27:02,077 17674   WARNING (kronos_file) hit locked row, resubmitted to queue
2020-06-27 14:27:02,078 17674   INFO    (kronos_file) updated 1 replicas
Exception in thread StompReceiverThread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/stomp/transport.py", line 351, in __receiver_loop
    self.process_frame(f, frame)
  File "/usr/lib/python2.7/site-packages/stomp/transport.py", line 193, in process_frame
    self.notify(frame_type, f.headers, f.body)
  File "/usr/lib/python2.7/site-packages/stomp/transport.py", line 250, in notify
    rtn = notify_func(headers, body)
  File "/usr/lib/python2.7/site-packages/rucio/daemons/tracer/kronos.py", line 130, in on_message
    self.__conn.ack(msg_id, self.__subscription_id)
  File "/usr/lib/python2.7/site-packages/stomp/protocol.py", line 278, in ack
    self.send_frame(CMD_ACK, headers)
  File "/usr/lib/python2.7/site-packages/stomp/protocol.py", line 248, in send_frame
    self.transport.transmit(frame)
  File "/usr/lib/python2.7/site-packages/stomp/transport.py", line 282, in transmit
    self.send(packed_frame)
  File "/usr/lib/python2.7/site-packages/stomp/transport.py", line 643, in send
    raise e
error: [Errno 32] Broken pipe

(cx_Oracle.DatabaseError) ORA-25405: transaction status unknown
(Background on this error at: http://sqlalche.me/e/4xp6)
2020-06-27 14:27:02,094 17674   ERROR   Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/tracer/kronos.py", line 275, in __update_atime
    if not touch_replica(replica):
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 374, in new_funct
    raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (cx_Oracle.DatabaseError) ORA-25405: transaction status unknown
(Background on this error at: http://sqlalche.me/e/4xp6)
```

**Comment by rcarpa** [comment]
I don't really know what I can do for this issue
