### ISSUE TITLE
Integrity error when deleting last replica

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#3965]
Motivation
----------
When deleting the last replica of a file I see the following traceback in the reaper log:

```
2020-08-27 13:05:44,961 6       INFO    Thread [0/1] :  Deletion ATTEMPT of test-v2.1:mc_v12-4GeV-1e-ecal_photonuclear-test_t1594763716.root as file:///projects/hep/fs9/shared/ldmx/ldcs/output/l
dmx/mc-data/v12/4.0GeV/v2.1test-2020-07-14/mc_v12-4GeV-1e-ecal_photonuclear-test_t1594763716.root on LUND
2020-08-27 13:05:44,961 6       WARNING Thread [0/1] :  Deletion NOTFOUND of test-v2.1:mc_v12-4GeV-1e-ecal_photonuclear-test_t1594763716.root as file:///projects/hep/fs9/shared/ldmx/ldcs/output/
ldmx/mc-data/v12/4.0GeV/v2.1test-2020-07-14/mc_v12-4GeV-1e-ecal_photonuclear-test_t1594763716.root on LUND
2020-08-27 13:05:44,961 6       INFO    Thread [0/1] :  1 files processed in 0.000700950622559 seconds
(psycopg2.IntegrityError) update or delete on table "dids" violates foreign key constraint "DID_META_FK" on table "did_meta"
DETAIL:  Key (scope, name)=(test-v2.1, mc_v12-4GeV-1e-ecal_photonuclear-test_t1594763716.root) is still referenced from table "did_meta".

[SQL: DELETE FROM dids WHERE dids.scope = %(scope_1)s AND dids.name = %(name_1)s]
[parameters: {'name_1': 'mc_v12-4GeV-1e-ecal_photonuclear-test_t1594763716.root', 'scope_1': 'test-v2.1'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-08-27 13:05:45,182 6       CRITICAL        Thread [0/1] :  Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/reaper/reaper2.py", line 523, in reaper
    delete_replicas(rse_id=rse_id, files=deleted_files)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 374, in new_funct
    raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (psycopg2.IntegrityError) update or delete on table "dids" violates foreign key constraint "DID_META_FK" on table "did_meta"
DETAIL:  Key (scope, name)=(test-v2.1, mc_v12-4GeV-1e-ecal_photonuclear-test_t1594763716.root) is still referenced from table "did_meta".

[SQL: DELETE FROM dids WHERE dids.scope = %(scope_1)s AND dids.name = %(name_1)s]
[parameters: {'name_1': 'mc_v12-4GeV-1e-ecal_photonuclear-test_t1594763716.root', 'scope_1': 'test-v2.1'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

Modification
------------

I guess the reaper should take care of deleting metadata when the last replica is deleted. Note that this is version 1.22.8 so maybe it has been fixed in the metadata restructuring in 1.23.

**Comment by davidgcameron** [comment]
Just to add that the replica seems to be stuck in the "B" state and the reaper is crashing like this on it every 10 mins.

**Comment by bari12** [comment]
Correct, the `core.delete_replicas` call also needs to cleanup the DIDMeta table. @tbeerman @cserf can any of you do this?

**Comment by tbeerman** [comment]
I can have a look.
