### ISSUE TITLE
Postgres failure in conveyor-finisher

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#410]
When looking through the logs for something else, I noticed the following:

```
==> /var/log/rucio/conveyor-finisher.log <==
Database exception.
Details: (psycopg2.ProgrammingError) column requests.estimated_started_at does not exist
LINE 1: ..., requests.submitter_id AS requests_submitter_id, requests.e...
                                                             ^
 [SQL: 'SELECT requests.id AS requests_id, requests.request_type AS requests_request_type, requests.scope AS requests_scope, requests.name AS requests_name, requests.did_type AS requests_did_type, requests.dest_rse_id AS requests_dest_rse_id, requests.source_rse_id AS requests_source_rse_id, requests.attributes AS requests_attributes, requests.state AS requests_state, requests.external_id AS requests_external_id, requests.external_host AS requests_external_host, requests.retry_count AS requests_retry_count, requests.err_msg AS requests_err_msg, requests.previous_attempt_id AS requests_previous_attempt_id, requests.rule_id AS requests_rule_id, requests.activity AS requests_activity, requests.bytes AS requests_bytes, requests.md5 AS requests_md5, requests.adler32 AS requests_adler32, requests.dest_url AS requests_dest_url, requests.submitted_at AS requests_submitted_at, requests.started_at AS requests_started_at, requests.transferred_at AS requests_transferred_at, requests.estimated_at AS requests_estimated_at, requests.submitter_id AS requests_submitter_id, requests.estimated_started_at AS requests_estimated_started_at, requests.estimated_transferred_at AS requests_estimated_transferred_at, requests.account AS requests_account, requests.requested_at AS requests_requested_at, requests.priority AS requests_priority, requests.updated_at AS requests_updated_at, requests.created_at AS requests_created_at \nFROM requests \nWHERE requests.state IN (%(state_1)s, %(state_2)s, %(state_3)s, %(state_4)s, %(state_5)s, %(state_6)s, %(state_7)s) AND requests.request_type IN (%(request_type_1)s, %(request_type_2)s, %(request_type_3)s) AND requests.updated_at < %(updated_at_1)s ORDER BY requests.updated_at ASC \n LIMIT %(param_1)s'] [parameters: {'updated_at_1': datetime.datetime(2017, 12, 19, 17, 11, 52, 245632), 'param_1': 1000, 'request_type_1': 'T', 'request_type_3': 'O', 'request_type_2': 'I', 'state_1': 'D', 'state_3': 'L', 'state_2': 'F', 'state_5': 'A', 'state_4': 'G', 'state_7': 'O', 'state_6': 'N'}]
2017-12-19 11:11:52,251	13154	ERROR	Thread [1/1] : Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/conveyor/finisher.py", line 109, in finisher
    thread=hb['assign_thread'], total_threads=hb['nr_threads'])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 274, in new_funct
    raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (psycopg2.ProgrammingError) column requests.estimated_started_at does not exist
LINE 1: ..., requests.submitter_id AS requests_submitter_id, requests.e...
                                                             ^
 [SQL: 'SELECT requests.id AS requests_id, requests.request_type AS requests_request_type, requests.scope AS requests_scope, requests.name AS requests_name, requests.did_type AS requests_did_type, requests.dest_rse_id AS requests_dest_rse_id, requests.source_rse_id AS requests_source_rse_id, requests.attributes AS requests_attributes, requests.state AS requests_state, requests.external_id AS requests_external_id, requests.external_host AS requests_external_host, requests.retry_count AS requests_retry_count, requests.err_msg AS requests_err_msg, requests.previous_attempt_id AS requests_previous_attempt_id, requests.rule_id AS requests_rule_id, requests.activity AS requests_activity, requests.bytes AS requests_bytes, requests.md5 AS requests_md5, requests.adler32 AS requests_adler32, requests.dest_url AS requests_dest_url, requests.submitted_at AS requests_submitted_at, requests.started_at AS requests_started_at, requests.transferred_at AS requests_transferred_at, requests.estimated_at AS requests_estimated_at, requests.submitter_id AS requests_submitter_id, requests.estimated_started_at AS requests_estimated_started_at, requests.estimated_transferred_at AS requests_estimated_transferred_at, requests.account AS requests_account, requests.requested_at AS requests_requested_at, requests.priority AS requests_priority, requests.updated_at AS requests_updated_at, requests.created_at AS requests_created_at \nFROM requests \nWHERE requests.state IN (%(state_1)s, %(state_2)s, %(state_3)s, %(state_4)s, %(state_5)s, %(state_6)s, %(state_7)s) AND requests.request_type IN (%(request_type_1)s, %(request_type_2)s, %(request_type_3)s) AND requests.updated_at < %(updated_at_1)s ORDER BY requests.updated_at ASC \n LIMIT %(param_1)s'] [parameters: {'updated_at_1': datetime.datetime(2017, 12, 19, 17, 11, 52, 245632), 'param_1': 1000, 'request_type_1': 'T', 'request_type_3': 'O', 'request_type_2': 'I', 'state_1': 'D', 'state_3': 'L', 'state_2': 'F', 'state_5': 'A', 'state_4': 'G', 'state_7': 'O', 'state_6': 'N'}]

2017-12-19 11:11:52,251	13154	INFO	Thread [1/1] : Sleeping for a while :  29.9860031605 seconds
```

Is this a new column?  Is it possible some schema evolution didn't get applied at the CMS instance (or maybe actually a "real" bug)?

**Comment by bari12** [comment]
It's a column which was introduced with the 1.14.0 feature release. It's in the #96 pull request.

**Comment by vingar** [comment]
reseting the db should solve this.

**Comment by bbockelm** [comment]
Gotcha, will close for now.
