### ISSUE TITLE
Poller fails on py3 with non-ascii characters in transfer error message

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#4177]
Motivation
----------
The poller on py3 throws an exception when it tries to insert an error messages from FTS which includes non-ascii characters:

```
Thread [39/72] : Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/core/request.py", line 1346, in update_request_state
    session=session)
  File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 393, in new_funct
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rucio/core/request.py", line 499, in set_request_state
    rowcount = session.query(models.Request).filter_by(id=request_id, external_id=transfer_id).update(update_items, synchronize_session=False)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3835, in update
    update_op.exec_()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1691, in exec_
    self._do_exec()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1884, in _do_exec
    self._execute_stmt(update_stmt)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1696, in _execute_stmt
    self.result = self.query._execute_crud(stmt, self.mapper)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_crud
    return conn.execute(stmt, self._params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1468, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 233: ordinal not in range(128)
```

Modification
------------

**Comment by bziemons** [comment]
Might be fixed in a newer version of sqlalchemy/cx_oracle. Let's retest in rucio 1.24 and put in a workaround if it still doesn't work then.
