### ISSUE TITLE
Trying to set is_new on dataset crashes

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#4192]
Motivation
----------
Making the following client call:

`client.set_metadata(scope='cms', name=did, key='is_new', value=True)
`

results in a crash of the server:

```
Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/rucio/web/rest/did.py", line 703, in POST
     issuer=ctx.env.get('issuer'), recursive=recursive, vo=ctx.env.get('vo'))
   File "/usr/lib/python2.7/site-packages/rucio/api/did.py", line 421, in set_metadata
     return did.set_metadata(scope=scope, name=name, key=key, value=value, recursive=recursive)
   File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 377, in new_funct
     result = function(*args, **kwargs)
   File "/usr/lib/python2.7/site-packages/rucio/core/did.py", line 1241, in set_metadata
     did_meta_plugins.set_metadata(scope=scope, name=name, key=key, value=value, recursive=recursive, session=session)
   File "/usr/lib/python2.7/site-packages/rucio/core/did_meta_plugins/__init__.py", line 103, in set_metadata
     meta_handler.set_metadata(scope, name, key, value, recursive, session=session)
   File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 393, in new_funct
     result = function(*args, **kwargs)
   File "/usr/lib/python2.7/site-packages/rucio/core/did_meta_plugins/json_meta.py", line 85, in set_metadata
     raise NotImplementedError

```

This seems to be a regression since this definitely worked before. It seems as if an exception is being thrown because we're not supporting JSON metadata even though this is not JSON metadata. 

The CLI command set-metadata fails with the same error

Modification
------------

**Comment by bari12** [comment]
As mentioned on Slack, I think it should be sufficient to add this here
https://github.com/rucio/rucio/blob/51b45d74817e8acbaf75e3fe80f0c9270d9b0a0a/lib/rucio/core/did_meta_plugins/did_column_meta.py#L51
Should be added to `1.24.0` (rc2?) and a hotfix `1.23.11.post3` release.
