### ISSUE TITLE
Declare all replicas of a file lost

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#42]
It would be very convenient for this command to declare all replicas of the files lost:

```
[dcameron@lxplus078] ~> rucio-admin replicas declare-bad --reason "bad guid metadata" mc15_13TeV:HITS.10672838._007007.pool.root.1 mc15_13TeV:HITS.10672838._007080.pool.root.1
No JSON object could be decoded
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.10.1/bin/rucio-admin", line 107, in new_funct
return function(*args, **kwargs)
File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.10.1/bin/rucio-admin", line 730, in declare_bad_file_replicas
non_declared = client.declare_bad_file_replicas(pfns=chunk, reason=args.reason)
File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.10.1/lib/python2.7/site-packages/rucio/client/replicaclient.py", line 43, in declare_bad_file_replicas
exc_cls, exc_msg = self._get_exception(headers=r.headers, status_code=r.status_code, data=r.content)
File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.10.1/lib/python2.7/site-packages/rucio/client/baseclient.py", line 191, in _get_exception
data = parse_response(data)
File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.10.1/lib/python2.7/site-packages/rucio/common/utils.py", line 193, in parse_response
return json.loads(data, object_hook=datetime_parser)
File "/usr/lib64/python2.6/json/_init_.py", line 318, in loads
return cls(encoding=encoding, **kw).decode(s)
File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

At least a proper error message should be returned instead of a stacktrace.

_Migrated from JIRA [RUCIO-2622](https://its.cern.ch/jira/browse/RUCIO-2622)_

**Comment by nikmagini** [comment]
Hi all,

IIUC the desired behavior is that all existing replicas of a file should be declared BAD when the LFN is passed as argument instead of the PFN, correct?

Should the file itself also be flagged in some way if all its replicas are BAD?

Thanks
N.

**Comment by bari12** [comment]
Yes, exactly. On the file itself I don't think that this has to be flagged, I think the necromancer daemon will do that then. @cserf maybe you can comment?

**Comment by cserf** [comment]
You just has to resolve the LFNs to the list of PFNs (list_replicas), then pass this list to declare_bad_file_replicas

**Comment by nikmagini** [comment]
OK.

Additional point: I can make the client resolve automatically if the user has passed LFN vs PFN.
But please let me know if you prefer instead that the user should specify this explicitly through an option.
