### ISSUE TITLE
Conveyor-submitter ranking comparison fails with py3

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4384]
Motivation
----------
```conveyor-submitter[42/43] : Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/core/transfer.py", line 1061, in get_transfer_requests_and_source_replicas
    if ranking >= avail_top_ranking or avail_top_ranking is None:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/conveyor/submitter.py", line 173, in submitter
    logger=logger)
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/conveyor/submitter.py", line 345, in __get_transfers
    failover_schemes=failover_schemes)
  File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 375, in new_funct
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rucio/core/transfer.py", line 1080, in get_transfer_requests_and_source_replicas
    logger(logging.CRITICAL, "Exception happened when trying to get transfer for request %s: %s" % (req_id), exc_info=True)
TypeError: not enough arguments for format string```
```

This is due to the fact that in py3 int cannot be compared to Nones.

Modification
------------
https://github.com/rucio/rucio/blob/7191097edd76a1f23eef0d79994727af125b40ce/lib/rucio/core/transfer.py#L1061
Flip the two conditions.

**Comment by bziemons** [comment]
Please also fix the logger here:
```diff
-    logger(logging.CRITICAL, "Exception happened when trying to get transfer for request %s: %s" % (req_id), exc_info=True)
+    logger(logging.CRITICAL, "Exception happened when trying to get transfer for request %s:" % (req_id), exc_info=True)
```
