### ISSUE TITLE
Crash when trying to find matching scheme

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#460]
From the CMS instance, I noticed this exception thrown in the `conveyor-transfer-submitter` after creating some minimal RSEs and trying to trigger a transfer
```
2018-01-11 20:59:36,983	4217	CRITICAL	Exception happened when trying to get transfer for request 8a818df9ca4047e3a6b36f95b98a5c7e: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/core/transfer.py", line 567, in get_transfer_requests_and_source_replicas
    scheme=current_schemes)
  File "/usr/lib/python2.7/site-packages/rucio/rse/rsemanager.py", line 640, in find_matching_scheme
    dest_candidates = sorted(dest_candidates, key=lambda k: k['domains'][domain][operation_dest])
  File "/usr/lib/python2.7/site-packages/rucio/rse/rsemanager.py", line 640, in <lambda>
    dest_candidates = sorted(dest_candidates, key=lambda k: k['domains'][domain][operation_dest])
KeyError: None
```

**Comment by bbockelm** [comment]
Here's the protocol definition for the available destination RSE:
```
Protocols:
==========
  gsiftp
    extended_attributes: None
    hostname: gftp.t2.ucsd.edu
    prefix: /hadoop/oppo
    domains: {u'wan': {u'read': 1, u'write': 1, u'third_party_copy': 0, u'delete': 1}, u'lan': {u'read': 0, u'write': 0, u'delete': 0}}
    scheme: gsiftp
    port: 0
    impl: rucio.rse.protocols.gfalv2.Default
```
and the source RSE:
```
Protocols:
==========
  gsiftp
    extended_attributes: None
    hostname: red-gridftp.unl.edu
    prefix: /dropfiles/cms/store
    domains: {u'wan': {u'read': 1, u'write': 1, u'third_party_copy': 0, u'delete': 1}, u'lan': {u'read': 0, u'write': 0, u'delete': 0}}
    scheme: gsiftp
    port: 0
    impl: rucio.rse.protocols.gfalv2.Default
```

**Comment by bbockelm** [comment]
This is the suspect line of code:

https://github.com/rucio/rucio/blob/master/lib/rucio/core/transfer.py#L566

When I remove the `domain=None` and just let it use the default keyword (`domain='wan'`), everything works.

However, that definitely wouldn't explain why transfers work for other folks though!

**Comment by mlassnig** [comment]
This looks like a regression from the latest WAN/LAN domain support patch! We actually have a domain called "third_party_copy" which we would like to use in the future (because it might be different than WAN data access priority), but it's not used yet.
