### ISSUE TITLE
Error in the light reaper with S3 RSEs

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#47]
```
4:24 PM
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/rucio/rse/protocols/s3boto.py", line 180, in connect
calling_format=OrdinaryCallingFormat())
File "/usr/lib/python2.7/site-packages/boto/init.py", line 141, in connect_s3
return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 191, in init
validate_certs=validate_certs, profile_name=profile_name)
File "/usr/lib/python2.7/site-packages/boto/connection.py", line 569, in init
host, config, self.provider, self._required_auth_capability())
File "/usr/lib/python2.7/site-packages/boto/auth.py", line 987, in get_auth_handler
ready_handlers.append(handler(host, config, provider))
File "/usr/lib/python2.7/site-packages/boto/auth.py", line 144, in init
HmacKeys.init(self, host, config, provider)
File "/usr/lib/python2.7/site-packages/boto/auth.py", line 81, in init
self.update_provider(provider)
File "/usr/lib/python2.7/site-packages/boto/auth.py", line 148, in update_provider
super(HmacAuthV1Handler, self).update_provider(provider)
File "/usr/lib/python2.7/site-packages/boto/auth.py", line 85, in update_provider
self._hmac = hmac.new(self._provider.secret_key.encode('utf-8'),
AttributeError: 'tuple' object has no attribute 'encode'
```

_Migrated from JIRA [RUCIO-2657](https://its.cern.ch/jira/browse/RUCIO-2657)_

**Comment by vingar** [comment]
this one is fixed
