### ISSUE TITLE
Traceback error in rucio upload

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#501]
Motivation
----------
```
[root@9c1d917353f9 /]# rucio -v --verbose upload --scope user.ewv --rse T2_US_NEBRASKA --name /store/data/Run2017A/SingleMuon/MINIAOD/PromptReco-v3/000/296/980/00000/3C8C839C-3256-E711-AD6B-02163E01A717.root /tmp/test.root 
2018-01-19 15:50:03,264 DEBUG   Extracting filesize (2161712084) and checksum (86e5e384) for file user.ewv:/store/data/Run2017A/SingleMuon/MINIAOD/PromptReco-v3/000/296/980/00000/3C8C839C-3256-E711-AD6B-02163E01A717.root
2018-01-19 15:50:03,267 DEBUG   Automatically setting new GUID
2018-01-19 15:50:03,346 DEBUG   Using account ewv
2018-01-19 15:50:03,346 DEBUG   Skipping dataset registration
2018-01-19 15:50:03,346 DEBUG   Processing file user.ewv:/store/data/Run2017A/SingleMuon/MINIAOD/PromptReco-v3/000/296/980/00000/3C8C839C-3256-E711-AD6B-02163E01A717.root for upload
2018-01-19 15:50:03,364 INFO    Adding replicas in Rucio catalog
2018-01-19 15:50:03,404 INFO    Replicas successfully added
2018-01-19 15:50:03,404 INFO    Adding replication rule on RSE T2_US_NEBRASKA for the file user.ewv:/store/data/Run2017A/SingleMuon/MINIAOD/PromptReco-v3/000/296/980/00000/3C8C839C-3256-E711-AD6B-02163E01A717.root
2018-01-19 15:50:06,514 ERROR   list index out of range
2018-01-19 15:50:06,515 ERROR   Rucio exited with an unexpected/unknown error. Please rerun the last command with the '-v' option and submit a ticket with all the available information to reproduce this error at https://its.cern.ch/jira/browse/RUCIO
2018-01-19 15:50:06,519 DEBUG   Traceback (most recent call last):
  File "/usr/bin/rucio", line 168, in new_funct
    return function(*args, **kwargs)
  File "/usr/bin/rucio", line 1082, in upload
    trace['protocol'] = rse_settings['protocols'][0]['scheme']
IndexError: list index out of range
Completed in 8.8367 sec.
```
Modification
------------

Expected behavior
-----------------

**Comment by vingar** [comment]
most likely due to no protocols registered at the destination RSE
