### ISSUE TITLE
Rucio 1.26.11 LTS Internal Error

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5249]
Motivation
----------
The integration action throws an error in `initialize tests`:
https://github.com/joeldierkes/rucio/runs/5230483160?check_suite_focus=true
```
[Thu Feb 17 10:35:58.074661 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332] DEBUG:root:Creating locks and replicas for rule 34268051495646e892432f423fe198fd [0/0/0]
[Thu Feb 17 10:35:58.074975 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332] DEBUG:root:Creating REPLICATING Lock test:752034fcea4c49018b797ba83e133484 on file1 for rule 34268051495646e892432f423fe198fd
[Thu Feb 17 10:35:58.082319 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332] DEBUG:root:Rule 34268051495646e892432f423fe198fd  [0/1/0] queued 0 transfers
[Thu Feb 17 10:35:58.085974 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332] ERROR:root:Internal Error
[Thu Feb 17 10:35:58.085988 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332] Traceback (most recent call last):
[Thu Feb 17 10:35:58.085992 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/web/rest/flaskapi/v1/common.py", line 66, in dispatch_request
[Thu Feb 17 10:35:58.085995 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     return super(ErrorHandlingMethodView, self).dispatch_request(*args, **kwargs)
[Thu Feb 17 10:35:58.085998 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 163, in dispatch_request
[Thu Feb 17 10:35:58.086007 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     return meth(*args, **kwargs)
[Thu Feb 17 10:35:58.086010 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/web/rest/flaskapi/v1/rules.py", line 216, in post
[Thu Feb 17 10:35:58.086013 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     vo=request.environ.get('vo'),
[Thu Feb 17 10:35:58.086016 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/api/rule.py", line 112, in add_replication_rule
[Thu Feb 17 10:35:58.086018 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     meta=meta)
[Thu Feb 17 10:35:58.086021 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 374, in new_funct
[Thu Feb 17 10:35:58.086024 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     result = function(*args, **kwargs)
[Thu Feb 17 10:35:58.086027 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/core/rule.py", line 360, in add_rule
[Thu Feb 17 10:35:58.086029 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     session=session)
[Thu Feb 17 10:35:58.086032 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 388, in new_funct
[Thu Feb 17 10:35:58.086035 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     result = function(*args, **kwargs)
[Thu Feb 17 10:35:58.086038 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/core/rule.py", line 3011, in __create_locks_replicas_transfers
[Thu Feb 17 10:35:58.086040 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     request_core.queue_requests(requests=transfers_to_create, session=session)
[Thu Feb 17 10:35:58.086043 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 388, in new_funct
[Thu Feb 17 10:35:58.086046 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     result = function(*args, **kwargs)
[Thu Feb 17 10:35:58.086048 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/core/request.py", line 161, in queue_requests
[Thu Feb 17 10:35:58.086051 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     record_counter('core.request.queue_requests')
[Thu Feb 17 10:35:58.086054 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/core/monitor.py", line 120, in record_counter
[Thu Feb 17 10:35:58.086057 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     COUNTERS[name] = counter = MultiCounter(statsd=name, labelnames=labels.keys() if labels else ())
[Thu Feb 17 10:35:58.086059 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/core/monitor.py", line 78, in __init__
[Thu Feb 17 10:35:58.086062 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     self._prom = self.init_prometheus_metric(prom, self._documentation, labelnames=labelnames, labelvalues=labelvalues)
[Thu Feb 17 10:35:58.086065 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/rucio/core/monitor.py", line 106, in init_prometheus_metric
[Thu Feb 17 10:35:58.086068 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     return Counter(name, documentation, labelnames=labelnames, labelvalues=labelvalues, registry=self._registry)
[Thu Feb 17 10:35:58.086074 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/prometheus_client/metrics.py", line 116, in __init__
[Thu Feb 17 10:35:58.086077 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     self._metric_init()
[Thu Feb 17 10:35:58.086079 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/prometheus_client/metrics.py", line 251, in _metric_init
[Thu Feb 17 10:35:58.086082 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     self._labelvalues)
[Thu Feb 17 10:35:58.086085 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/prometheus_client/values.py", line 56, in __init__
[Thu Feb 17 10:35:58.086088 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     self.__reset()
[Thu Feb 17 10:35:58.086107 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/prometheus_client/values.py", line 70, in __reset
[Thu Feb 17 10:35:58.086110 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     files[file_prefix] = MmapedDict(filename)
[Thu Feb 17 10:35:58.086113 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]   File "/usr/local/lib/python3.6/site-packages/prometheus_client/mmap_dict.py", line 61, in __init__
[Thu Feb 17 10:35:58.086116 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332]     self._f = open(filename, 'rb' if read_mode else 'a+b')
[Thu Feb 17 10:35:58.086120 2022] [wsgi:error] [pid 138:tid 140119432357632] [remote 172.18.0.2:42332] FileNotFoundError: [Errno 2] No such file or directory: '/tmp/prometheus/counter_138.db'
```

Modification
------------
Fix the error.

**Comment by rcarpa** [comment]
I assume it comes from https://github.com/rucio/containers/pull/180/files#diff-dc2e86802a20a9eb13f8ddd90914fd044e84f7e49486fe84ccf0cf28c10989a8R126  Creating the /tmp/prometheus directory in the rucio/dev container and re-building the image should fix the issue ; alternatively, removing this line and re-building the dev image should also fix the issue

**Comment by rcarpa** [comment]
Is this one fixed ?

**Comment by maany** [comment]
I haven't made any progress on this yet. @joeldierkes are you working on this one?

**Comment by joeldierkes** [comment]
As discussed yesterday I will rerun the action.

**Comment by joeldierkes** [comment]
https://github.com/rucio/containers/commit/a3e17c2cc62877e4ce6c9d8501b51dc0bdbcc247 Should've fixed the issue, right?

**Comment by rcarpa** [comment]
I wasn't clear enough in the message. This "should" be fixed since https://github.com/rucio/containers/commit/e343e510b1dd888b46d5ef99a1da473a0b27fee2  ; I'm just asking to see if it is indeed fixed and if we can close the ticket

**Comment by joeldierkes** [comment]
Okay. I'll notify you as soon as I have the result of the pipeline. (It is this one: https://github.com/rucio/rucio/runs/5246197077?check_suite_focus=true)

**Comment by joeldierkes** [comment]
The pipeline is fixed now, the changes @rcarpa made worked.
