### ISSUE TITLE
UploadClient does not respect --ca-certificate

### ISSUE THREAD

**Issue by bjwhite-fnal** [rucio/rucio#5263]
The UploadClient doesn't seem to be using the value of the `--ca-certificate` argument during calls to `upload()`.

```
(rucio-client) [bjwhite@lsst-devl01 ~]$ pip list | grep rucio-clients
rucio-clients (1.26.9)

(rucio-client) [bjwhite@lsst-devl01 ~]$ echo ${CA_CERT_DIR}
/home/daues/certificates.osg35.1.89-1/certificates

(rucio-client) [bjwhite@lsst-devl01 ~]$ rucio ping
2022-02-20 11:24:32,760 ERROR   Could not find a suitable TLS CA certificate bundle, invalid path: /etc/grid-security/certificates
2022-02-20 11:24:32,760 ERROR
Rucio exited with an unexpected/unknown error.
Please rerun the last command with the "-v" option to gather more information.
If you're sure there is a problem with Rucio itself, please follow up at: https://github.com/rucio/rucio/issues


(rucio-client) [bjwhite@lsst-devl01 ~]$ rucio --ca-certificate ${CA_CERT_DIR} ping
1.26.4

(rucio-client) [bjwhite@lsst-devl01 ~]$ rucio -v --ca-certificate ${CA_CERT_DIR} upload --rse SLAC_TESTDISK --scope user.bjwhite --register-after-upload --recursive testdata3/
2022-02-20 12:04:18,237 DEBUG   uploadclient.py Appended dataset with DID user.bjwhite:/home/bjwhite/testdata3
2022-02-20 12:04:18,242 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file10
2022-02-20 12:04:18,246 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file9
2022-02-20 12:04:18,250 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file2
2022-02-20 12:04:18,254 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file1
2022-02-20 12:04:18,258 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file5
2022-02-20 12:04:18,262 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file4
2022-02-20 12:04:18,267 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file3
2022-02-20 12:04:18,271 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file8
2022-02-20 12:04:18,275 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file7
2022-02-20 12:04:18,279 DEBUG   uploadclient.py Appended file with DID user.bjwhite:file6
2022-02-20 12:04:18,588 INFO    Created dataset with DID user.bjwhite:testdata3
2022-02-20 12:04:18,588 DEBUG   uploadclient.py Num. of files that upload client is processing: 10
2022-02-20 12:04:18,663 DEBUG   rucio   Traceback (most recent call last):
  File "/home/bjwhite/rucio-client/bin/rucio", line 141, in new_funct
    return function(*args, **kwargs)
  File "/home/bjwhite/rucio-client/bin/rucio", line 983, in upload
    upload_client.upload(items, summary_file_path)
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/rucio/client/uploadclient.py", line 148, in upload
    rse_settings = self.rses.setdefault(rse, rsemgr.get_rse_info(rse, vo=self.client.vo))
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/rucio/rse/rsemanager.py", line 97, in get_rse_info
    rse_info = __request_rse_info(str(rse), vo=vo, rse_id=rse_id, session=session)  # NOQA pylint: disable=undefined-variable
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/rucio/rse/__init__.py", line 58, in get_rse_client
    return client.get_rse(rse)
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/rucio/client/rseclient.py", line 68, in get_rse
    r = self._send_request(url, type='GET')
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/rucio/client/baseclient.py", line 398, in _send_request
    result = self.session.get(url, headers=hds, verify=verify, timeout=self.timeout, params=params, stream=True, cert=cert, auth=auth)
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/home/bjwhite/rucio-client/lib64/python3.6/site-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/grid-security/certificates

2022-02-20 12:04:18,664 ERROR   Could not find a suitable TLS CA certificate bundle, invalid path: /etc/grid-security/certificates
2022-02-20 12:04:18,664 ERROR
Rucio exited with an unexpected/unknown error.
Please rerun the last command with the "-v" option to gather more information.
If you're sure there is a problem with Rucio itself, please follow up at: https://github.com/rucio/rucio/issues
Completed in 0.4367 sec.
```

**Comment by bjwhite-fnal** [comment]
I'll note that I had `ca_cert = /etc/grid-security/certificates` in the client section of my rucio.cfg file. However, I would expect the CLI to override that.

**Comment by dchristidis** [comment]
Note that the WebDAV protocol implementation, that is used in the example, is not fit for purpose. It hardcodes the CA path to `/etc/grid-security/certificates`, yet disables the certificate verification in each request. Go figure.

Fixing this issue will be covered as part of #6632 and #6633.

**Comment by bari12** [comment]
Closing, will be followed in #6632
