### ISSUE TITLE
protocol preference for upload ignored for stats

### ISSUE THREAD

**Issue by ygrange** [rucio/rucio#5459]
Motivation
----------
I want to be able to upload files using `rucio upload` using only the OIDC authentication flow. This requires me to tell rucio what protocol to use (ie webdav). I can do this with the `--protocol` flag. However a `rucio upload` consists of a stat, an upload and another stat. 

It looks like the first stat at least, but possibly also the second one, still picks any of the available protocols for an RSE, meaning I get asked for my certificate quite often. 

Modification
------------
Making sure that all calls to the storage use the protocol as specified by the protocols command line option

**Comment by ygrange** [comment]
And here output of an upload that fails because of this:
```Singularity> rucio -vvv upload test2.txt --rse DESY-DCACHE --scope MATCHMAKER_UVA_DVOHL --protocol davs --register-after-upload
2022-04-05 12:57:42,590	DEBUG	uploadclient.py	Num. of files that upload client is processing: 1
2022-04-05 12:57:42,970	DEBUG	uploadclient.py	Input validation done.
2022-04-05 12:57:42,971	INFO	Preparing upload for file test2.txt
2022-04-05 12:57:43,018	DEBUG	uploadclient.py	wan domain is used for the upload
2022-04-05 12:57:43,028	DEBUG	logging.py	gfal.Default: connecting to storage
2022-04-05 12:57:43,061	DEBUG	logging.py	gfal.Default: checking if file exists None
2022-04-05 12:57:43,062	DEBUG	rsemanager.py	Checking if davs://dcache-door-doma01.desy.de:2880//escape/wp2_rucio_testbed/desy_dcache/MATCHMAKER_UVA_DVOHL/1c/c6/test2.txt exists
2022-04-05 12:57:43,062	DEBUG	logging.py	gfal.Default: checking if file exists davs://dcache-door-doma01.desy.de:2880//escape/wp2_rucio_testbed/desy_dcache/MATCHMAKER_UVA_DVOHL/1c/c6/test2.txt
2022-04-05 12:57:43,780	DEBUG	logging.py	gfal.Default: closing protocol connection
2022-04-05 12:57:43,782	DEBUG	uploadclient.py	[{'hostname': 'dcache-door-doma01.desy.de', 'scheme': 'davs', 'port': 2880, 'prefix': '//escape/wp2_rucio_testbed/desy_dcache', 'impl': 'rucio.rse.protocols.gfal.Default', 'domains': {'lan': {'read': 1, 'write': 1, 'delete': 1}, 'wan': {'read': 1, 'write': 1, 'delete': 1, 'third_party_copy': 1}}, 'extended_attributes': None}]
2022-04-05 12:57:43,782	INFO	Trying upload with davs to DESY-DCACHE
2022-04-05 12:57:43,782	DEBUG	uploadclient.py	Processing upload with the domain: wan
2022-04-05 12:57:43,782	DEBUG	logging.py	gfal.Default: connecting to storage
2022-04-05 12:57:43,783	DEBUG	logging.py	gfal.Default: connecting to storage
2022-04-05 12:57:43,784	DEBUG	uploadclient.py	The PFN created from the LFN: davs://dcache-door-doma01.desy.de:2880//escape/wp2_rucio_testbed/desy_dcache/MATCHMAKER_UVA_DVOHL/1c/c6/test2.txt
2022-04-05 12:57:43,784	DEBUG	logging.py	gfal.Default: checking if file exists root://dcache-se-doma.desy.de:1094//escape/wp2_rucio_testbed/desy_dcache/MATCHMAKER_UVA_DVOHL/1c/c6/test2.txt
2022-04-05 12:57:45,310	WARNING	Upload attempt failed
2022-04-05 12:57:45,310	INFO	Exception: The requested service is not available at the moment.
Details: An unknown exception occurred.
Details: Failed to stat file (Invalid exchange)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/protocols/gfal.py", line 532, in __gfal2_exist
    if ctx.stat(str(path)):
gfal2.GError: Failed to stat file (Invalid exchange)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/protocols/gfal.py", line 370, in exists
    status = self.__gfal2_exist(path)
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/protocols/gfal.py", line 538, in __gfal2_exist
    raise exception.RucioException(error)
rucio.common.exception.RucioException: An unknown exception occurred.
Details: Failed to stat file (Invalid exchange)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/client/uploadclient.py", line 283, in upload
    sign_service=sign_service)
  File "/usr/local/lib/python3.6/site-packages/rucio/client/uploadclient.py", line 607, in _upload_item
    if protocol_write.overwrite is False and delete_existing is False and protocol_read.exists(readpfn):
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/protocols/gfal.py", line 377, in exists
    raise exception.ServiceUnavailable(error)
rucio.common.exception.ServiceUnavailable: The requested service is not available at the moment.
Details: An unknown exception occurred.
Details: Failed to stat file (Invalid exchange)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'escape-rucio.cern.ch'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
2022-04-05 12:57:45,515	ERROR	Failed to upload file test2.txt
2022-04-05 12:57:45,516	ERROR	None of the given files have been uploaded.
```

**Comment by rizart** [comment]
Hello,

I think the issue is on `protocol_read.exists` because the scheme is not forced for `protocol_read`. What @ygrange describes is accurate for the 1.26.11 client indeed. I see that this is fixed from 1.27.8 onwards. If this is confirmed, then we need to first upgrade our ESCAPE Rucio instance before being able to use the uploads reliably with tokens. Any thoughts from people more familiar with that part of the code are welcomed.

**Comment by bari12** [comment]
For the protocols there was quite some changes in 1.27 and 1.28. For an upload we do not jump around between read/write protocols anymore, but use the write protocol for everything. There is multiple reasons for that, mostly to avoid race conditions between namespace syncs of storage nodes, but this should also help in this case actually.

**Comment by paulmillar** [comment]
I guess the problem here is with the client, rather than with the server.  If so, would things still work if the client were upgrade to v1.27 or v1.28 while the server remained at v1.26?

I'm asking because it would be nice to avoid putting pressure on @rizart (to upgrade the server) unnecessarily.

Cheers,
Paul.

**Comment by rizart** [comment]
Hello Paul,

Well, that's the issue, 1.27* onwards clients are not compatible with 1.26* servers.
In any case, we will upgrade our instance by the end of this month, so this will be solved then (along with other goodies that will come with the new servers ;p).

**Comment by bari12** [comment]
Yes, this is a change in the client. 
But in general we don't really support running newer clients with older server versions, if it jumps major releases, within one major release is ok. Since the clients might assume that some functionality is available on the server, which might not be.

**Comment by rizart** [comment]
I assume we can close this issue @ygrange ?

**Comment by ygrange** [comment]
Yup! Even better: I can close it myself!
