### ISSUE TITLE
Config not found RuntimeError in version 1.29.0rc1

### ISSUE THREAD

**Issue by sfayer** [rucio/rucio#5704]
Hi,

It seems that version 1.29.0rc1 has started requiring a config file again and throws a RuntimeError if it isn't present:
```
>>> from rucio.client import Client
...
RuntimeError: Could not load Rucio configuration file. Rucio looked in the following paths for a configuration file, in order:
        /opt/rucio/etc/rucio.cfg
```
(Full stack trace below).

This import without a config file used to work without error in 1.28.7 (the context of this is within DIRAC where we import the rucio.client module and configure it at runtime without the file).

I did a bisect and the change in behaviour was in this commit:
https://github.com/rucio/rucio/commit/c3e376863b80d4234355c6aed2e0f87b3aa603da
Specifically, the new `get_legacy_config` function can also throw a RuntimeError if the config file doesn't exist, perhaps it'd be possible just to catch that and continue, maybe something simple like the following?

```patch
@@ -60,7 +60,11 @@ def config_get(section, option, raise_exception=True, default=None, clean_cached
     try:
         return extract_function(get_config(), section, option)
     except (ConfigParser.NoOptionError, ConfigParser.NoSectionError, RuntimeError) as err:
-        legacy_config = get_legacy_config(section, option, extract_function)
+        legacy_config = None
+        try:
+            legacy_config = get_legacy_config(section, option, extract_function)
+        except RuntimeError:
+            pass
         if legacy_config is not None:
             return legacy_config
```

I think we've had problems like this before... I don't know whether it'd be possible to add a test to catch if this happening? E.g. a unit test to check that rucio.client can be imported successfully when no config is present.

Regards,
Simon

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "testenv/rucio/lib/rucio/client/__init__.py", line 16, in <module>
    from .client import Client  # noqa: F401
  File "testenv/rucio/lib/rucio/client/client.py", line 20, in <module>
    from rucio.client.accountclient import AccountClient
  File "testenv/rucio/lib/rucio/client/accountclient.py", line 21, in <module>
    from rucio.client.baseclient import BaseClient
  File "testenv/rucio/lib/rucio/client/baseclient.py", line 53, in <module>
    LOG = setup_logger(module_name=__name__)
  File "testenv/rucio/lib/rucio/common/utils.py", line 1482, in setup_logger
    if _force_cfg_log_level(cfg_opt):
  File "testenv/rucio/lib/rucio/common/utils.py", line 1457, in _force_cfg_log_level
    cfg_forced_modules = config_get('logging', cfg_option, raise_exception=False, default=None, clean_cached=True,
  File "testenv/rucio/lib/rucio/common/config.py", line 63, in config_get
    legacy_config = get_legacy_config(section, option, extract_function)
  File "testenv/rucio/lib/rucio/common/config.py", line 100, in get_legacy_config
    if config_has_option(section, option):
  File "testenv/rucio/lib/rucio/common/config.py", line 124, in config_has_option
    return get_config().has_option(section, option)
  File "testenv/rucio/lib/rucio/common/config.py", line 369, in get_config
    __CONFIG = Config()
  File "testenv/rucio/lib/rucio/common/config.py", line 396, in __init__
    raise RuntimeError('Could not load Rucio configuration file. '
RuntimeError: Could not load Rucio configuration file. Rucio looked in the following paths for a configuration file, in order:
        /opt/rucio/etc/rucio.cfg
```

**Comment by joeldierkes** [comment]
Ahh yes, the check for the `RuntimeError` is missing. My bad. Good catch. :+1:

**Comment by joeldierkes** [comment]
#5041 was the previous one, it appeared there in the `is_client` utils function.

Yes, the test is a good idea! :tada: And thank you for such a detailed Issue, it helped a lot! :smiley_cat:

**Comment by sfayer** [comment]
Splendid, thanks for patching it so quickly :smile:

**Comment by bari12** [comment]
I'll add this one to the `Rucio 1.29.0rc2` 👍 Thanks @sfayer and @joeldierkes
