### ISSUE TITLE
foreign key error on deleting dids in reaper

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5733]
Motivation
----------
```
2022-07-13 08:32:24,129 root    1       CRITICAL        reaper[2b317444f2:0/41]: Exception
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.IntegrityError: ORA-02292: integrity constraint (ATLAS_RUCIO.DATASET_LOCKS_DID_FK) violated - child record found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 388, in new_funct
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rucio/core/replica.py", line 1542, in delete_replicas
    __delete_replicas(rse_id, files, ignore_availability=ignore_availability, session=session)
  File "/usr/local/lib/python3.6/site-packages/rucio/core/replica.py", line 1624, in __delete_replicas
    rse_id=rse_id, files=files, session=session)
  File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 402, in new_funct
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rucio/core/replica.py", line 2015, in __cleanup_after_replica_deletion
    session.execute(stmt)
  File "<string>", line 2, in execute
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1491, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (cx_Oracle.IntegrityError) ORA-02292: integrity constraint (ATLAS_RUCIO.DATASET_LOCKS_DID_FK) violated - child record found
[SQL: DELETE /*+ INDEX(DIDS DIDS_PK) */ FROM atlas_rucio.dids WHERE EXISTS (SELECT 1 
FROM atlas_rucio."TEMPORARY_SCOPE_NAME_0" 
WHERE atlas_rucio.dids.scope = atlas_rucio."TEMPORARY_SCOPE_NAME_0".scope AND atlas_rucio.dids.name = atlas_rucio."TEMPORARY_SCOPE_NAME_0".name)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/reaper/reaper.py", line 642, in _run_once
    delete_replicas(rse_id=rse.id, files=deleted_files)
  File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 395, in new_funct
    raise DatabaseException(str(error))
rucio.common.exception.DatabaseException: Database exception.
Details: (cx_Oracle.IntegrityError) ORA-02292: integrity constraint (ATLAS_RUCIO.DATASET_LOCKS_DID_FK) violated - child record found
[SQL: DELETE /*+ INDEX(DIDS DIDS_PK) */ FROM atlas_rucio.dids WHERE EXISTS (SELECT 1 
FROM atlas_rucio."TEMPORARY_SCOPE_NAME_0" 
WHERE atlas_rucio.dids.scope = atlas_rucio."TEMPORARY_SCOPE_NAME_0".scope AND atlas_rucio.dids.name = atlas_rucio."TEMPORARY_SCOPE_NAME_0".name)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by bari12** [comment]
Related issue with a description #372 

But I don't get the description. To me this just shouldn't happen. If there is a rule on the container, why would it delete a file (the last one?) in a dataset at all. The only explanation I have is: Dataset was detached from the container. All the locks were removed from the replicas in the container correctly, but the dataset_lock on the dataset was not removed.
@cserf ?

**Comment by rcarpa** [comment]
Should I re-assign this one to @cserf  ?

**Comment by cserf** [comment]
After a bit of investigation, I think that the problem is in the `detach_did` workflow. The following lines :
https://github.com/rucio/rucio/blob/1f10818974abd07681b7f3b74c430ca20ccb41b4/lib/rucio/core/rule.py#L2458-L2468
do remove the dataset locks from the children if the detached DID is a container. But there is no check if the detached DID is a dataset. In this case, we should get the parents from the dataset and remove the dataset locks (if any) for the rules on the parents.

**Comment by cserf** [comment]
Reassigning the ticket to @bari12  :D
