### ISSUE TITLE
reaper fails when run with --scheme on rses without given scheme

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5791]
Motivation
----------

Recently this error was reported. reaper was running on this rse with --scheme != 'https', the only scheme supported by this rse. 

```
2022-08-09 16:23:54,929 root    10      DEBUG   reaper[0/1] list_and_mark_unlocked_replicas on ......  for 1000000000000 bytes in 0.6920185089111328 seconds: 100 replicas
2022-08-09 16:23:54,929 root    10      CRITICAL        reaper[0/1] Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/reaper/reaper.py", line 589, in reaper
    prot = rsemgr.create_protocol(rse_info, 'delete', scheme=scheme, logger=logger)
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/rsemanager.py", line 195, in create_protocol
    protocol_attr = select_protocol(rse_settings, operation, scheme, domain)
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/rsemanager.py", line 166, in select_protocol
    candidates = _get_possible_protocols(rse_settings, operation, scheme, domain)
  File "/usr/local/lib/python3.6/site-packages/rucio/rse/rsemanager.py", line 142, in _get_possible_protocols
    ' found : %s.' % str(rse_settings))
rucio.common.exception.RSEProtocolNotSupported: RSE does not support requested protocol.
Details: No protocol for provided settings found : {'availability_delete': True, 'availability_read': True, 'availability_write': True, 'credentials': None, 'deterministic': True, 'domain': ['lan', 'wan'], 'id': 'b69808ffe0b14f6ead3c23ea171b0710', 'lfn2pfn_algorithm': 'hash', 'protocols': [{'hostname': '.....', 'scheme': 'https', 'port': 2880, 'prefix': '/dune/scratch/rucio_test', 'impl': 'rucio.rse.protocols.gfalv2.Default', 'domains': {'lan': {'read': 1, 'write': 1, 'delete': 1}, 'wan': {'read': 1, 'write': 1, 'delete': 1, 'third_party_copy': 20}}, 'extended_attributes': None}], 'qos_class': None, 'rse': '........', 'rse_type': 'DISK', 'sign_url': None, 'staging_area': False, 'verify_checksum': True, 'volatile': False, 'read_protocol': 1, 'write_
protocol': 1, 'delete_protocol': 1, 'third_party_copy_protocol': 1}.
```

Modification
------------
Do we want to handle this case more gracefully ?

**Comment by bari12** [comment]
We should, it probably should just skip it then? (with a log line?)
