### ISSUE TITLE
allow to disable statsd log collection

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5879]
Motivation
----------

Statsd client tries to connect by default to a server and handles badly name resolution failures: 

```
Traceback (most recent call last):
  File "/usr/local/bin/rucio-judge-cleaner", line 24, in <module>
    from rucio.daemons.judge.cleaner import run, stop
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/judge/cleaner.py", line 34, in <module>
    from rucio.core.monitor import record_counter
  File "/usr/local/lib/python3.6/site-packages/rucio/core/monitor.py", line 79, in <module>
    CLIENT = StatsClient(host=SERVER, port=PORT, prefix=SCOPE)
  File "/usr/local/lib/python3.6/site-packages/statsd/client/udp.py", line 35, in __init__
    host, port, fam, socket.SOCK_DGRAM)[0]
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Modification
------------

We may want to allow people to disable statsd collection all together.

**Comment by rcarpa** [comment]
Done in 1.30
