### ISSUE TITLE
Clients receives generic HTTP error 500 when calling `list-datasets-rse`

### ISSUE THREAD

**Issue by faluchet** [rucio/rucio#6014]
### Description

My suspicion is that this is triggered by "big results" for `list_datasets_per_rse`, somewhere between the server->client response.
`core` and `api` methods are not affected, while the snippet below consistently fails.

### Steps to reproduce

```
>>> from rucio.client.replicaclient import ReplicaClient
>>> rclient=ReplicaClient()
>>> rclient.list_datasets_per_rse('CERN-PROD_DATADISK')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/faluchet/.local/lib/python3.6/site-packages/rucio/client/replicaclient.py", line 397, in list_datasets_per_rse
    raise exc_cls(exc_msg)
rucio.common.exception.RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 500)
```
Verbose output is of no help, e.g.,
```
$ rucio -v list-datasets-rse CERN-PROD_DATADISK
[...]
2022-12-07 10:32:18,266	DEBUG	baseclient.py	HTTP request: GET https://voatlasrucio-server-prod.cern.ch:443/replicas/rse/CERN-PROD_DATADISK
2022-12-07 10:32:18,266	DEBUG	baseclient.py	HTTP header:  X-Rucio-Auth-Token: [hidden]
2022-12-07 10:32:18,267	DEBUG	baseclient.py	HTTP header:  X-Rucio-VO: def
2022-12-07 10:32:18,267	DEBUG	baseclient.py	HTTP header:  Connection: Keep-Alive
2022-12-07 10:32:18,267	DEBUG	baseclient.py	HTTP header:  User-Agent: rucio-clients/1.29.7.post1
2022-12-07 10:32:18,267	DEBUG	baseclient.py	HTTP header:  X-Rucio-Script: rucio::-v
2022-12-07 10:32:18,267	DEBUG	baseclient.py	HTTP header:  X-Rucio-Account: faluchet
2022-12-07 10:35:42,295	DEBUG	baseclient.py	HTTP Response: 500 Internal Server Error
2022-12-07 10:35:42,296	DEBUG	baseclient.py	Response text (length=532): [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 rucio-admin@cern.ch to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
]
2022-12-07 10:35:42,296	ERROR	An unknown exception occurred.
Details: no error information passed (http status code: 500)
```

**Comment by bari12** [comment]
It's very likely that this is happening because it is a huge query. However a better error would still be something to aim for.
Does it work fine for you on smaller RSEs?

**Comment by faluchet** [comment]
All good for smaller RSE, I'd also point the finger to huge queries indeed.
Not sure how to optimally patch it myself tho.

**Comment by bari12** [comment]
Honestly, I am not really sure if we can do much here. A better exception would of course be great, but it is not easy to detect, since in our case (ATLAS) these long queries are killed by the database. But by trying to do something smarter with the exceptions, we actually might hide "real" errors.

**Comment by haozturk** [comment]
CMS observes this error as well. Similar to what reported above, it works well with small RSEs while it throws error for large ones:
```
$ rucio list-datasets-rse T2_US_Florida
2024-04-29 10:28:17,657	ERROR	An unknown exception occurred.
Details: no error information passed (http status code: 500)

$ rucio list-datasets-rse T2_TR_METU
SCOPE:NAME
----------
cms:/ADDGravTo2G_NegInt-0_LambdaT-10000_M-1000To2000_TuneCP5_13p6TeV_pythia8/Run3Summer22DRPremix-124X_mcRun3_2022_realistic_v12-v2/AODSIM#7d601e60-70e9-40c4-b7ac-d204b8164062
...
```

**Comment by bari12** [comment]
In the end this depends on the httpd configuration of your rucio instance. At ATLAS, we kill everything longer than 5 minutes, I imagine something similar is happening in CMS.

**Comment by bari12** [comment]
Thank you for raising this. We have reviewed this issue as part of our regular issue review.

We see value in this request, but we do not have the capacity to work on it within the next twelve months.

In line with our [issue management guideline](https://rucio.cern/documentation/developer/issue_management), we are labelling it `wishlist` and closing it. This does not mean it is forgotten: wishlist items are revisited regularly during component reviews and roadmap planning, and this issue can be re-opened and added back to the pipeline as soon as interest and capacity align.
