### ISSUE TITLE
Cannot access when having no token

### ISSUE THREAD

**Issue by d-ylee** [rucio/rucio#6099]
### Description

After the changes to authentication from 1.29.10 to 1.29.11, accessing the WebUI with no token or a non-existing token is not possible. Since `rucio.core.authentication.validate_token` now `raise CannotAuthenticate` and is not guaranteed a value on return, it is possible for `rucio.web.ui.flask.common.utils.validate_webui_token` to have an error that is not caught when an exception is raised when no token or a non existing token is sent from the webui.

### Steps to reproduce

1. Start a browser session with a token that is not in the database, or a fresh new browser session that has no token (i.e. Private Browsing session)
2. Access Rucio WebUI

### Rucio Version

WebUI: 1.29.11

##### Normal Session (Non-existing Rucio Token)
```
[Fri Feb 24 15:07:52.754316 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219] Traceback (most recent call last):
[Fri Feb 24 15:07:52.754325 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
[Fri Feb 24 15:07:52.754338 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     response = self.full_dispatch_request()
[Fri Feb 24 15:07:52.754345 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
[Fri Feb 24 15:07:52.754352 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     rv = self.handle_user_exception(e)
[Fri Feb 24 15:07:52.754358 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
[Fri Feb 24 15:07:52.754365 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     rv = self.dispatch_request()
[Fri Feb 24 15:07:52.754377 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
[Fri Feb 24 15:07:52.754387 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Fri Feb 24 15:07:52.754396 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/rucio/web/ui/flask/bp.py", line 142, in <lambda>
[Fri Feb 24 15:07:52.754421 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     return lambda: authenticate(template=template, title=title)
[Fri Feb 24 15:07:52.754432 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/rucio/web/ui/flask/common/utils.py", line 599, in authenticate
[Fri Feb 24 15:07:52.754437 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     valid_token_dict = validate_webui_token()
[Fri Feb 24 15:07:52.754441 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/rucio/web/ui/flask/common/utils.py", line 226, in validate_webui_token
[Fri Feb 24 15:07:52.754445 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     valid_token_dict = auth.validate_auth_token(session_token)
[Fri Feb 24 15:07:52.754449 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 388, in new_funct
[Fri Feb 24 15:07:52.754453 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     result = function(*args, **kwargs)
[Fri Feb 24 15:07:52.754457 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/rucio/api/authentication.py", line 293, in validate_auth_token
[Fri Feb 24 15:07:52.754484 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     auth = authentication.validate_auth_token(token, session=session)
[Fri Feb 24 15:07:52.754495 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 402, in new_funct
[Fri Feb 24 15:07:52.754499 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     result = function(*args, **kwargs)
[Fri Feb 24 15:07:52.754503 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]   File "/usr/local/lib/python3.6/site-packages/rucio/core/authentication.py", line 443, in validate_auth_token
[Fri Feb 24 15:07:52.754508 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219]     raise CannotAuthenticate(traceback.format_exc())
[Fri Feb 24 15:07:52.754511 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219] rucio.common.exception.CannotAuthenticate: Cannot authenticate.
[Fri Feb 24 15:07:52.754523 2023] [wsgi:error] [pid 20:tid 140600083212032] [client 10.100.2.1:1219] Details: NoneType: None
```

##### In Private Browsing Session (No Rucio Token)
```
[Fri Feb 24 15:13:04.159848 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565] Traceback (most recent call last):
[Fri Feb 24 15:13:04.159853 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
[Fri Feb 24 15:13:04.159857 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     response = self.full_dispatch_request()
[Fri Feb 24 15:13:04.159860 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
[Fri Feb 24 15:13:04.159862 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     rv = self.handle_user_exception(e)
[Fri Feb 24 15:13:04.159864 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
[Fri Feb 24 15:13:04.159867 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     rv = self.dispatch_request()
[Fri Feb 24 15:13:04.159869 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
[Fri Feb 24 15:13:04.159871 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Fri Feb 24 15:13:04.159873 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/rucio/web/ui/flask/bp.py", line 142, in <lambda>
[Fri Feb 24 15:13:04.159876 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     return lambda: authenticate(template=template, title=title)
[Fri Feb 24 15:13:04.159879 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/rucio/web/ui/flask/common/utils.py", line 599, in authenticate
[Fri Feb 24 15:13:04.159881 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     valid_token_dict = validate_webui_token()
[Fri Feb 24 15:13:04.159884 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/rucio/web/ui/flask/common/utils.py", line 226, in validate_webui_token
[Fri Feb 24 15:13:04.159886 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     valid_token_dict = auth.validate_auth_token(session_token)
[Fri Feb 24 15:13:04.159888 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 388, in new_funct
[Fri Feb 24 15:13:04.159891 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     result = function(*args, **kwargs)
[Fri Feb 24 15:13:04.159894 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/rucio/api/authentication.py", line 293, in validate_auth_token
[Fri Feb 24 15:13:04.159905 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     auth = authentication.validate_auth_token(token, session=session)
[Fri Feb 24 15:13:04.159908 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 402, in new_funct
[Fri Feb 24 15:13:04.159910 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     result = function(*args, **kwargs)
[Fri Feb 24 15:13:04.159912 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]   File "/usr/local/lib/python3.6/site-packages/rucio/core/authentication.py", line 426, in validate_auth_token
[Fri Feb 24 15:13:04.159916 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565]     raise CannotAuthenticate("No token was passed!")
[Fri Feb 24 15:13:04.159986 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565] rucio.common.exception.CannotAuthenticate: Cannot authenticate.
[Fri Feb 24 15:13:04.159991 2023] [wsgi:error] [pid 18:tid 140600083212032] [client 10.100.2.1:61565] Details: No token was passed!

```
It seems like the token I had in the browser was invalid after I haven’t accessed the WebUI for 2 weeks. This was when I first encountered the first traceback. I then tried a private browsing session, which then I encountered the second traceback.

After some troubleshooting, it seems like the issue is that the exception is not properly handled in the `validate_webui_token`. Previously, if a token was expired or no token was provided, the `validate_auth_token` function in `rucio/core/authentication.py` would return None, which would allow `validate_webui_token` to run without an exception.
https://github.com/rucio/rucio/blob/2838612c8609c1810012c9c00521f571c4b7676b/lib/rucio/core/authentication.py#L439

Now that `rucio.core.authentication.validate_token` does not `return None` and instead `raise CannotAuthenticate`, `validate_webui_token` would cause HTTP 500 due to not being able to handle the error.
https://github.com/rucio/rucio/blob/85492437ace81e6957a713d3d8895309703ded36/lib/rucio/core/authentication.py#L440

**Comment by bari12** [comment]
@maany can you please have a look on this. It is very likely related to the change #5986

**Comment by dciangot** [comment]
we are observing a similar (afaict identical) behavior updating CMS from 1.29.6 to 1.30.4 (as mentioned at the meeting @bari12 ) . Is it possible?
And, in case, how could we fix this? I don't understand if there is a fix already.

**Comment by bari12** [comment]
Yes, I think that's possible. I don't know why it still works for ATLAS though, but there is something broken due to #5986

**Comment by dchristidis** [comment]
ATLAS was not affected because we stuck to 1.30.3 on the nodes running the Web UI. :grimacing:

**Comment by bari12** [comment]
Backport 1.29.12
