### ISSUE TITLE
Error creating config file when starting `rucio-clients` docker-image

### ISSUE THREAD

**Issue by maxnoe** [rucio/rucio#6463]
### Description

When running the `rucio-clients` docker image as shown in the documentation (but without the -d flag) results in an error creating the config file.

### Steps to reproduce

```
❯ docker run \
  -e RUCIO_CFG_RUCIO_HOST=https://server.rucio:443 \
  -e RUCIO_CFG_AUTH_HOST=https://auth.rucio:443 \
  -e RUCIO_CFG_AUTH_TYPE=userpass \
  -e RUCIO_CFG_USERNAME=ddmlab \
  -e RUCIO_CFG_PASSWORD=secret \
  -e RUCIO_CFG_ACCOUNT=root \
  --name=rucio-client \
  -it rucio/rucio-clients
File rucio.cfg not found. It will generate one.
INFO:root:Merged 16 configuration values from /opt/user/rucio.default.cfg
Traceback (most recent call last):
  File "/usr/local/rucio_client/merge_rucio_configs.py", line 147, in <module>
    merge_configs(args.source or [], args.destination, use_env=args.use_env)
  File "/usr/local/rucio_client/merge_rucio_configs.py", line 128, in merge_configs
    env_config = fix_multi_word_sections(load_flat_config(env_config))
  File "/usr/local/rucio_client/merge_rucio_configs.py", line 59, in load_flat_config
    section, option = flat_key.split('_', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
Enable shell completion on the rucio commands
```

The error happens on `RUCIO_CFG_ACCOUNT`, it doesn't have  an `_` so the split fails.

### Rucio Version

32.8, 33

**Comment by maxnoe** [comment]
Seems to be a duplicate of this issue here: https://github.com/rucio/containers/issues/267
