### ISSUE TITLE
Reaper fails to delete files in S3 based RSEs

### ISSUE THREAD

**Issue by marcoverl** [rucio/rucio#6548]
Deletion of files in S3 based RSEs failed for two reasons:
1)   File "/usr/lib64/python3.9/threading.py", line 1414, in _register_atexit raise RuntimeError("can't register atexit after shutdown"):
it can be fixed by doing:
`sed -i '/import threading/i import concurrent.futures.thread' /usr/local/lib/python3.9/site-packages/rucio/daemons/reaper/reaper.py`
as suggested [here](https://github.com/python/cpython/issues/86813#issuecomment-1246098699)

2) stat operation on a file path containing the URL signature when using  rucio.rse.protocols.gfal.NoRename fails, probably because the signature was done for the delete operation.  It can be fixed patching the __gfal2_exist function:
`sed -i '/if ctx.stat(str(path)):/i\            if not self.renaming: return 0' /usr/local/lib/python3.9/site-packages/rucio/rse/protocols/gfal.py`

**Comment by bari12** [comment]
@cserf @mlassnig For the second issue, I thought there is a solution already, or am I misremembering this?

**Comment by rdimaio** [comment]
Issue 1 from this issue's description was also discussed in these slides at the 2024 Rucio workshop: https://indico.cern.ch/event/1343110/contributions/6117049/attachments/2937883/5160670/Rucio4ItaDL-ATroja.pdf

> Reaper daemon doesn’t work unless we import “threading” and “concurrent.futures.thread”;

The solution proposed (`sed -i '/import threading/i import concurrent.futures.thread' /usr/local/lib/python3.9/site-packages/rucio/daemons/reaper/reaper.py`) fixes that error message in particular, but I assume it would cause the rest of the Reaper code to break, as soon as we import something from `threading`. 

Until https://github.com/python/cpython/issues/86813 is resolved, the proper workaround seems to be the one mentioned here https://github.com/python/cpython/issues/86813#issuecomment-1246097184

Could you post the full traceback for the error message if possible?

**Comment by rdimaio** [comment]
https://github.com/rucio/rucio/pull/7111 this might fix the issue, but let's doublecheck after merging

**Comment by marcoverl** [comment]
> Issue 1 from this issue's description was also discussed in these slides at the 2024 Rucio workshop: https://indico.cern.ch/event/1343110/contributions/6117049/attachments/2937883/5160670/Rucio4ItaDL-ATroja.pdf
> 
> > Reaper daemon doesn’t work unless we import “threading” and “concurrent.futures.thread”;
> 
> The solution proposed (`sed -i '/import threading/i import concurrent.futures.thread' /usr/local/lib/python3.9/site-packages/rucio/daemons/reaper/reaper.py`) fixes that error message in particular, but I assume it would cause the rest of the Reaper code to break, as soon as we import something from `threading`.

'import threading' is still there, i just added the line 'import concurrent.futures.thread' below that

> 
> Until [python/cpython#86813](https://github.com/python/cpython/issues/86813) is resolved, the proper workaround seems to be the one mentioned here [python/cpython#86813 (comment)](https://github.com/python/cpython/issues/86813#issuecomment-1246097184)
> 
> Could you post the full traceback for the error message if possible?

This is the error message:
[...]
2024-03-04 13:43:03,512 root    7       DEBUG   [0/1]: Deletion ATTEMPT of cygno-analysis:SGA/TRJ/test_new_db_2 as https://minio-dc.cloud.infn.it:443/cygno-analysis/SGA/TRJ/test_new_db_2 on BACKBONE_USERDISK
2024-03-04 13:43:03,515 botocore.hooks  7       DEBUG   Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f319ab8dee0>
2024-03-04 13:43:03,517 botocore.hooks  7       DEBUG   Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f319ac000d0>
2024-03-04 13:43:03,517 botocore.hooks  7       DEBUG   Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f319b02b430>
2024-03-04 13:43:03,521 root    7       CRITICAL        [0/1]: Deletion CRITICAL of cygno-analysis:SGA/TRJ/test_new_db_2 as https://minio-dc.cloud.infn.it:443/cygno-analysis/SGA/TRJ/test_new_db_2 on BACKBONE_USERDISK in 0.01 seconds : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rucio/daemons/reaper/reaper.py", line 169, in delete_from_storage
    pfn = get_signed_url(rse_id, rse_info['sign_url'], 'delete', pfn)
  File "/usr/local/lib/python3.9/site-packages/rucio/core/credential.py", line 170, in get_signed_url
    s3 = boto3.client(service_name='s3',
  File "/usr/local/lib/python3.9/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 145, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 198, in _create_client_class
    self._event_emitter.emit(
  File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/boto3/utils.py", line 65, in _handler
    module = import_module(module)
  File "/usr/local/lib/python3.9/site-packages/boto3/utils.py", line 56, in import_module
    __import__(name)
  File "/usr/local/lib/python3.9/site-packages/boto3/s3/inject.py", line 16, in <module>
    from boto3.s3.transfer import (
  File "/usr/local/lib/python3.9/site-packages/boto3/s3/transfer.py", line 131, in <module>
    from s3transfer.futures import NonThreadedExecutor
  File "/usr/local/lib/python3.9/site-packages/s3transfer/__init__.py", line 373, in <module>
    class MultipartUploader:
  File "/usr/local/lib/python3.9/site-packages/s3transfer/__init__.py", line 388, in MultipartUploader
    executor_cls=concurrent.futures.ThreadPoolExecutor,
  File "/usr/lib64/python3.9/concurrent/futures/__init__.py", line 49, in __getattr__
    from .thread import ThreadPoolExecutor as te
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 37, in <module>
    threading._register_atexit(_python_exit)
  File "/usr/lib64/python3.9/threading.py", line 1414, in _register_atexit
    raise RuntimeError("can't register atexit after shutdown")
RuntimeError: can't register atexit after shutdown

**Comment by rdimaio** [comment]
Thanks - seems like the issue occurs within the boto3 module - I found this relevant issue https://github.com/boto/boto3/issues/3221

According to https://github.com/boto/boto3/issues/3221#issuecomment-1421526634, this workaround https://github.com/rucio/rucio/pull/7111 should still work in this context

**Comment by marcoverl** [comment]
Very good. And what about the issue 2? Is there already a solution as pointed out by @bari12 ?

**Comment by bari12** [comment]
Backport 35.6.1

**Comment by marcoverl** [comment]
Hello, what about the issue 2. stat operation on a file path containing the URL signature when using rucio.rse.protocols.gfal.NoRename fails, probably because the signature was done for the delete operation. I temporary fixed it by patching the __gfal2_exist function at line 515 of gfal.py:
sed -i '/if ctx.stat(str(path)):/i\            if not self.renaming: return 0' /usr/local/lib/python3.9/site-packages/rucio/rse/protocols/gfal.py

**Comment by rdimaio** [comment]
> @cserf @mlassnig For the second issue, I thought there is a solution already, or am I misremembering this?

pinging this regarding the second issue
