### ISSUE TITLE
attach_dids does not handle bad (non-existing) dids enough :)

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#6571]
### Description

A call to `attach_dids` results in an internal server error while trying to raise an exception.
https://github.com/rucio/rucio/blob/1fc0c97416844ab81abca478558bd0091777c354/lib/rucio/core/did.py#L665

This is the trace in the server

```
"Internal Error
    tuple indices must be integers or slices, not str
      File "/usr/local/lib/python3.9/site-packages/rucio/web/rest/flaskapi/v1/common.py", line 90, in dispatch_request
        return super(ErrorHandlingMethodView, self).dispatch_request(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 190, in dispatch_request
        return current_app.ensure_sync(meth)(**kwargs)
      File "/usr/local/lib/python3.9/site-packages/rucio/web/rest/flaskapi/v1/dids.py", line 861, in post
        attach_dids(scope=scope, name=name, attachment=attachments, issuer=request.environ.get('issuer'), vo=request.environ.get('vo'))
      File "/usr/local/lib/python3.9/site-packages/rucio/db/sqla/session.py", line 454, in new_funct
        result = function(*args, session=session, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rucio/api/did.py", line 194, in attach_dids
        dids = did.attach_dids(scope=scope, name=name, dids=attachment['dids'],
      File "/usr/local/lib/python3.9/site-packages/rucio/db/sqla/session.py", line 468, in new_funct
        result = function(*args, session=session, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rucio/core/did.py", line 270, in attach_dids
        return attach_dids_to_dids(attachments=[{'scope': scope, 'name': name, 'dids': dids, 'rse_id': rse_id}], account=account, session=session)
      File "/usr/local/lib/python3.9/site-packages/rucio/db/sqla/session.py", line 468, in new_funct
        result = function(*args, session=session, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rucio/core/did.py", line 329, in attach_dids_to_dids
        __add_collections_to_container(parent_did=parent_did,
      File "/usr/local/lib/python3.9/site-packages/rucio/db/sqla/session.py", line 468, in new_funct
        result = function(*args, session=session, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rucio/core/did.py", line 665, in __add_collections_to_container
        raise exception.DataIdentifierNotFound("Data identifier '%(scope)s:%(name)s' not found" % row)
      File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 48, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
    "
    ```

### Steps to reproduce

Try attaching a non existent did to a container.
```client.attach_dids('user.rchauhan', 'my/test-container/USER', dids=[{'scope':'user.wrongscope', 'name':'/my/test-dataset/USER#123'}])```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    client.attach_dids('user.rchauhan', 'my/test-container/USER', dids=[{'scope':'user.wrongscope', 'name':'/my/test-dataset/USER#123'}])
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel8/py3/current/lib/python3.6/site-packages/rucio/client/didclient.py", line 197, in attach_dids
    raise exc_cls(exc_msg)
rucio.common.exception.RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 500)
```

**Comment by bari12** [comment]
We have reviewed this issue as part of our regular issue review.

This issue has been open for longer than the twelve-month delivery horizon, but we are making an exception and keeping it open. 

Currently being worked on by @bari12 

In line with our [issue management guideline](https://rucio.cern/documentation/developer/issue_management), such exceptions are granted case by case, and no issue remains open for longer than twenty-four months. By then this issue will be resolved, re-justified, or closed and labelled `wishlist`.

**Comment by bari12** [comment]
This is already fixed by https://github.com/rucio/rucio/pull/8074
Closing this as duplucate
