### ISSUE TITLE
Make WebDAV protocols on par with GFAL

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#6633]
### Description

The dependency on GFAL made sense in the era of SRM and GridFTP. However, their use is expected to diminish or disappear entirely, in favour of WebDAV and XRootD. In addition, the long-term future of the GFAL libraries is not certain.

We should prop up the existing implementations and encourage the Rucio communities to start using them.

### Motivation

Lay the groundwork for potentially removing the dependency on GFAL in the future.

### Change

The exact work necessary is not known. This will require some coordination with the operations teams to test the existing implementations and identify their shortcomings.

Note that we can focus on one protocol first and postpone working on the other, if necessary.

**Comment by dchristidis** [comment]
One major annoyance that we’ll need to overcome is that `requests` does not support the `dav://` and `davs://` schemes.

```python
>>> import requests
>>> requests.get('dav://example.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'dav://example.com'
```

https://github.com/psf/requests/blob/a3ce6f007597f14029e6b6f54676c34196aa050e/src/requests/sessions.py#L446-L449

I though we could register a new adapter, but then `urllib3`  complains.

```python
>>> session = requests.session()
>>> session.mount('dav://', requests.adapters.HTTPAdapter())
>>> session.get('dav://example.com')
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 454, in send
    conn = self.get_connection(request.url, proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 356, in get_connection
    conn = self.poolmanager.connection_from_url(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/poolmanager.py", line 299, in connection_from_url
    return self.connection_from_host(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/poolmanager.py", line 246, in connection_from_host
    return self.connection_from_context(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/poolmanager.py", line 258, in connection_from_context
    raise URLSchemeUnknown(scheme)
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme dav

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 456, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Not supported URL scheme dav
```

https://github.com/urllib3/urllib3/blob/5bc41f5e1569fbdaee38daf9c82641b9702ed52a/src/urllib3/poolmanager.py#L150-L157

**Comment by bari12** [comment]
Thank you for raising this. We have reviewed this issue as part of our regular issue review.

This issue has been open for longer than the twelve-month delivery horizon, but we are making an exception and keeping it open. 

I'll give this an exception to be worked on in the next 12m.

In line with our [issue management guideline](https://rucio.cern/documentation/developer/issue_management), such exceptions are granted case by case, and no issue remains open for longer than twenty-four months. By then this issue will be resolved, re-justified, or closed and labelled `wishlist`.
