### ISSUE TITLE
`test_conveyor` consistently failing

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6751]
There's a consistent issue with test_conveyor. It seems to have begun 2 days ago: https://github.com/rucio/rucio/actions/workflows/integration_tests.yml

I'm not sure if this might be related to the MySQL8 autotest issue: https://github.com/rucio/rucio/issues/6747

These are the failing tests:
```
 =========================== short test summary info ============================
FAILED tests/test_conveyor.py::test_preparer_throttler_submitter[file_config_mock{'conveyor': {'use_preparer': 'true'}}] - AssertionError: assert 1.0 == 0
FAILED tests/test_conveyor.py::test_transfer_plugins[file_config_mock{'transfers': {'fts3tape_metadata_plugins': 'activity'}, 'tape_priority': {'fast': '100', 'slow': '1'}}] - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> != <RequestSta...
FAILED tests/test_conveyor.py::test_multihop_intermediate_replica_lifecycle[caches_mock0-core_config_mock{'transfers': {'multihop_tombstone_delay': -1}}] - AssertionError: assert <ReplicaState.COPYING: 'C'> == <ReplicaState.AVAILAB...
FAILED tests/test_conveyor.py::test_fts_non_recoverable_failures_handled_on_multihop[caches_mock0] - TypeError: argument of type 'NoneType' is not iterable
FAILED tests/test_conveyor.py::test_fts_recoverable_failures_handled_on_multihop[caches_mock0] - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_receiver_archiving[caches_mock0] - assert False
FAILED tests/test_conveyor.py::test_non_deterministic_dst[caches_mock0] - AssertionError: assert <ReplicaState.COPYING: 'C'> == <ReplicaState.AVAILAB...
FAILED tests/test_conveyor.py::test_lost_transfers - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_overwrite_on_tape[caches_mock0] - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_overwrite_hops[caches_mock0] - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fts', port=8...
FAILED tests/test_conveyor.py::test_file_exists_handled[caches_mock0] - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_overwrite_corrupted_files[caches_mock0-core_config_mock{'transfers': {'overwrite_corrupted_files': False}}] - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_two_multihops_same_intermediate_rse[file_config_mock{'transfers': {'stats_enabled': 'True'}}-caches_mock0-core_config_mock{'transfers': {'multihop_tombstone_delay': -1, 'multihop_rse_expression': '*'}}] - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_checksum_validation - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_multisource_receiver - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_multihop_receiver_on_failure[caches_mock0] - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_multihop_receiver_on_success[caches_mock0] - AssertionError: assert <RequestState.SUBMISSION_FAILED: 'A'> == <RequestSta...
FAILED tests/test_conveyor.py::test_cancel_rule - TypeError: sequence item 0: expected str instance, NoneType found
FAILED tests/test_conveyor.py::test_transfer_with_tokens[file_config_mock{'oidc': {'admin_issuer': 'indigoiam'}}] - assert False
FAILED tests/test_conveyor.py::test_stager - AssertionError: assert <ReplicaState.COPYING: 'C'> == <ReplicaState.AVAILAB...
FAILED tests/test_conveyor.py::test_multisource[caches_mock0] - AssertionError: assert 'XRD1' == 'XRD4'
======= 21 failed, 4 passed, 1 skipped, 29 warnings in 865.90s (0:14:25) =======
Error: Process completed with exit code 1.
```

**Comment by rdimaio** [comment]
Looking at the [logs](https://github.com/rucio/rucio/actions/runs/8929780635/job/24528405318), there seems to be a transfertool-related issue:

```
WARNING  root:fts3.py:1041 Could not submit transfer to https://fts:8446 - HTTPSConnectionPool(host='fts', port=8446): Max retries exceeded with url: /jobs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f049883de80>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING  root:fts3.py:1054 Failed to submit transfer to https://fts:8446, error: None
ERROR    root:common.py:448 Failed to submit a job with error Wrong answer returned by the transfer tool.
Details: No transfer id returned by https://fts:8446
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rucio/daemons/conveyor/common.py", line 442, in _submit_transfers
    eid = transfertool_obj.submit(transfers, job_params, timeout)
  File "/usr/local/lib/python3.9/site-packages/rucio/transfertool/fts3.py", line 1058, in submit
    raise TransferToolWrongAnswer('No transfer id returned by %s' % self.external_host)
rucio.common.exception.TransferToolWrongAnswer: Wrong answer returned by the transfer tool.
```

There have been no changes merged to master in the last week, and this is the latest commit: https://github.com/rucio/rucio/commit/2c389be05cd37ab81cae35e4f49ff905a5efa00f. The tests for this commit passed without issues: https://github.com/rucio/rucio/actions/runs/8849088942/job/24300244993

I am guessing that this is an issue of one of the CI/CD dependencies using a new version, causing something to break.

**Comment by rdimaio** [comment]
Comparing these two runs:
- successful: https://github.com/rucio/rucio/actions/runs/8849088942/job/24303470601
- failing: https://github.com/rdimaio/rucio/actions/runs/8924801874/job/24511970763

Where this is the only diff: https://github.com/rucio/rucio/compare/master...rdimaio:rucio:patch-6588-core-account

These are the differences in Python dependencies installed:
```
23c23
< blinker-1.8.1
---
> blinker-1.7.0
48c48
< filelock-3.14.0
---
> filelock-3.13.4
115c115
< referencing-0.35.1
---
> referencing-0.35.0
```

For these three dependencies, I don't see any relevant issues on GH at first glance:
- https://github.com/pallets-eco/blinker/releases/tag/1.8.1
- https://github.com/tox-dev/filelock/releases/tag/3.14.0
- https://github.com/python-jsonschema/referencing/releases/tag/v0.35.1

**Comment by rdimaio** [comment]
In the test initialization, for the failing test, there is [this error log](https://github.com/rdimaio/rucio/actions/runs/8924801874/job/24511970763#step:9:403):

```
Bad endpoint: https://fts:8446 (HTTPSConnectionPool(host='fts', port=8446): Max retries exceeded with url: // (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b1e58e970>: Failed to establish a new connection: [Errno 111] Connection refused')))
```

Which is not present for the [successful execution](https://github.com/rucio/rucio/actions/runs/8850495568/job/24309147258#step:9:413).



Another interesting one:
- Here's this successful execution from 2024-04-30: https://github.com/rucio/rucio/actions/runs/8893655155/attempts/1
- By re-running that same job, with the same commit hash, directly from GH, it fails: https://github.com/rucio/rucio/actions/runs/8893655155 (you can see the list of attempts in the top right):

![image](https://github.com/rucio/rucio/assets/35903974/e8d887b6-f21f-4fe1-bcec-1b796abb5849)

**Comment by rdimaio** [comment]
Checked the image cache build for the autotests as well, no diff other than the one mentioned here https://github.com/rucio/rucio/issues/6751#issuecomment-2092992123.

I compared these two builds:
- https://github.com/rucio/rucio/actions/runs/8872808007/job/24357680519, from 2024-04-29
- https://github.com/rucio/rucio/actions/runs/8933617945/job/24539277065, from 2024-05-03

**Comment by rdimaio** [comment]
This issue was indeed related to the MySQL8 issue (https://github.com/rucio/rucio/issues/6747). Pinning `mysql:8.3` for `ftsdb` (https://github.com/rdimaio/rucio/commit/d6dc4e65fb6d2523346f041bb1587be5424ff4aa) fixed the issue:

https://github.com/rdimaio/rucio/actions/runs/8969270791/job/24630347377#step:18:102
