### ISSUE TITLE
Rucio Client crashes with 500 on client.get_rse_limits

### ISSUE THREAD

**Issue by voetberg** [rucio/rucio#6954]
### Description

If you try to run rse info it doesn't work, the source of the issue is in client.get_rse_limits. 

### Steps to reproduce

$ rucio-admin rse add {some rse} 
$ rucio-admin rse info {some rse} <- Throws a 500 

Error log: 

```
[root@0c0508bcaafc rucio]# rucio-admin -v rse info MOCK_12345678
An unknown exception occurred.
Details: no error information passed (http status code: 500)
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/opt/rucio/bin/rucio-admin", line 108, in new_funct
    return function(*args, **kwargs)
  File "/opt/rucio/bin/rucio-admin", line 544, in info_rse
    rse_limits = client.get_rse_limits(args.rse)
  File "/opt/rucio/lib/rucio/client/rseclient.py", line 633, in get_rse_limits
    raise exc_cls(exc_msg)
rucio.common.exception.RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 500)

Completed in 0.0930 sec.
```

The same thing happens with the python client, reproducibility script: 
```
rse_factory = TemporaryRSEFactory(vo=vo, name_prefix=name_prefix)
rse,_ = rse_factory.make_posix_rse()  # Fresh RSE
c.get_rse_limits(rse)

c.get_rse_limits("MOCK4") # Old RSE
```

### Rucio Version

Dev image - client 34.0.0

**Comment by bari12** [comment]
I think the issue is that when you call get_rse_limits it always assumes that there actually is at least one.

**Comment by dchristidis** [comment]
Superseded by #7087.
