### ISSUE TITLE
Restricted (oidc) token size limiting group membership

### ISSUE THREAD

**Issue by robbarnsley** [rucio/rucio#7136]
### Description

Trying to auth (oidc) when the user's token is large (>2048 characters) violates column size constraint `oauth_requests.redirect_msg`. 

One consequence of this is that a user can only be a member of a finite number of groups.

Server logs:

```
[Tue Oct 22 08:02:13.719070 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 2024-10-22 08:02:13,719\toic.oauth2.message\t25\tDEBUG\tJWS header: {'kid': 'rsa1', 'alg': 'RS256'}
[Tue Oct 22 08:02:13.719134 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 2024-10-22 08:02:13,719\toic.oauth2.message\t25\tDEBUG\tFound signing key.
[Tue Oct 22 08:02:13.719263 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 2024-10-22 08:02:13,719\tjwkest.jws\t25\tDEBUG\tPicking key by key type=RSA
[Tue Oct 22 08:02:13.719326 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 2024-10-22 08:02:13,719\tjwkest.jws\t25\tDEBUG\tPicking key based on alg=RS256, kid=rsa1 and use=
[Tue Oct 22 08:02:13.719390 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 2024-10-22 08:02:13,719\tjwkest.jws\t25\tDEBUG\tPicked: kid:rsa1, use:, kty:RSA
[Tue Oct 22 08:02:13.720474 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 2024-10-22 08:02:13,720\tjwkest.jws\t25\tDEBUG\tVerified message using key with kid=rsa1
[Tue Oct 22 08:02:13.728853 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 2024-10-22 08:02:13,728\troot\t25\tDEBUG\tTraceback (most recent call last):
[Tue Oct 22 08:02:13.728864 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
[Tue Oct 22 08:02:13.728867 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     cursor, statement, parameters, context
[Tue Oct 22 08:02:13.728869 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
[Tue Oct 22 08:02:13.728871 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     cursor.execute(statement, parameters)
[Tue Oct 22 08:02:13.728873 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] psycopg2.errors.StringDataRightTruncation: value too long for type character varying(2048)
[Tue Oct 22 08:02:13.728875 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 
[Tue Oct 22 08:02:13.728877 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 
[Tue Oct 22 08:02:13.728879 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] The above exception was the direct cause of the following exception:
[Tue Oct 22 08:02:13.728881 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 
[Tue Oct 22 08:02:13.728883 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] Traceback (most recent call last):
[Tue Oct 22 08:02:13.728885 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib/python3.6/site-packages/rucio/core/oidc.py", line 471, in get_token_oidc
[Tue Oct 22 08:02:13.728887 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     models.OAuthRequest.redirect_msg: new_token['token']})
[Tue Oct 22 08:02:13.728889 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3279, in update
[Tue Oct 22 08:02:13.728891 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     execution_options={"synchronize_session": synchronize_session},
[Tue Oct 22 08:02:13.728893 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
[Tue Oct 22 08:02:13.728895 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     result = conn._execute_20(statement, params or {}, execution_options)
[Tue Oct 22 08:02:13.728905 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
[Tue Oct 22 08:02:13.728907 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     return meth(self, args_10style, kwargs_10style, execution_options)
[Tue Oct 22 08:02:13.728909 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
[Tue Oct 22 08:02:13.728911 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     self, multiparams, params, execution_options
[Tue Oct 22 08:02:13.728913 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1491, in _execute_clauseelement
[Tue Oct 22 08:02:13.728915 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     cache_hit=cache_hit,
[Tue Oct 22 08:02:13.728917 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
[Tue Oct 22 08:02:13.728919 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     e, statement, parameters, cursor, context
[Tue Oct 22 08:02:13.728921 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
[Tue Oct 22 08:02:13.728923 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
[Tue Oct 22 08:02:13.728925 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
[Tue Oct 22 08:02:13.728927 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     raise exception
[Tue Oct 22 08:02:13.728929 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
[Tue Oct 22 08:02:13.728931 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     cursor, statement, parameters, context
[Tue Oct 22 08:02:13.728933 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
[Tue Oct 22 08:02:13.728935 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220]     cursor.execute(statement, parameters)
[Tue Oct 22 08:02:13.728937 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(2048)
[Tue Oct 22 08:02:13.728939 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] 
[Tue Oct 22 08:02:13.728941 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] [SQL: UPDATE rucio.oauth_requests SET access_msg=%(access_msg)s, redirect_msg=%(redirect_msg)s, updated_at=%(updated_at)s WHERE rucio.oauth_requests.state = %(state_1)s]
[Tue Oct 22 08:02:13.728943 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] [parameters: {'access_msg': 'F93..', 'redirect_msg': 'eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiI5YmY0MDczZi1mNDZiLTQ1Y2UtYjg2Yi01OGNkMjI2MzZmYmMiLCJpc3MiOiJodHRwczpcL1wvc2thLWlhbS5zdGZjLmFjLnVrXC ... (1823 characters truncated) ... _y1eaM-6SuHRbkBx_xw13NiF-_LQ7PjWo5K_zSzQQKfe2aOXWFVLyJ7weaVlouWDuNf59w9JgEJBRU5ZSv-JnSZSmAes3KGLTl2Fx9hFDYLX3XbTkMgsjbiMT8sy2HrkS3dzS_giufk1fkC2yxPwQ', 'updated_at': datetime.datetime(2024, 10, 22, 8, 2, 13, 726944), 'state_1': 'kqhjlS6RJgnhkWU2yoKcRvCCgRVUfSf0bWwLeEpwpgaTQGTkgJ'}]
[Tue Oct 22 08:02:13.728949 2024] [wsgi:error] [pid 25:tid 139816716429056] [remote 10.10.199.218:60220] (Background on this error at: https://sqlalche.me/e/14/9h9h)

```

### Steps to reproduce

1. Add user to a significant number of IAM groups (~25, but depends on length of group names, hierarchy etc.)

2. Try `whoami`.

### Rucio Version

1.29.6

**Comment by robbarnsley** [comment]
This is obvious, but just for completeness, I resolved this on our instance by altering the table column size constraint (2048>4096).
