### ISSUE TITLE
Client setup fails on Windows at `get_rucio_version` step

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#7138]
### Description

Full log:

```
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      requirement found install_requires requests>=2.32.2
      requirement found install_requires urllib3>=1.26.18
      requirement found install_requires dogpile-cache>=1.2.2
      requirement found install_requires tabulate>=0.9.0
      requirement found install_requires jsonschema>=4.20.0
      requirement found ssh paramiko>=3.4.0
      requirement found sftp paramiko>=3.4.0
      requirement found kerberos kerberos>=1.3.1
      requirement found kerberos pykerberos>=1.2.4
      requirement found kerberos requests-kerberos>=0.14.0
      requirement found swift python-swiftclient>=4.4.0
      requirement found argcomplete argcomplete>=3.1.6
      requirement found dumper python-magic>=0.4.27
      Traceback (most recent call last):
        File "C:\Users\dento\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\dento\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dento\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\dento\AppData\Local\Temp\pip-build-env-vsz51nnr\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dento\AppData\Local\Temp\pip-build-env-vsz51nnr\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\dento\AppData\Local\Temp\pip-build-env-vsz51nnr\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 56, in <module>
        File "C:\Users\dento\AppData\Local\Temp\pip-install-wajponwr\rucio-clients_2241ae7440b44d1fb5a869042edaeab4\setuputil.py", line 118, in get_rucio_version
          ver = run_shell_command(
              "PYTHONPATH=lib " + python_executable + " -c "
              '"from rucio import version; print(version.version_string())"'
          )
        File "C:\Users\dento\AppData\Local\Temp\pip-install-wajponwr\rucio-clients_2241ae7440b44d1fb5a869042edaeab4\setuputil.py", line 109, in run_shell_command
          output = subprocess.Popen(["/bin/sh", "-c", cmd], stdout=subprocess.PIPE)
        File "C:\Users\dento\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1036, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              pass_fds, cwd, env,
                              ^^^^^^^^^^^^^^^^^^^
          ...<5 lines>...
                              gid, gids, uid, umask,
                              ^^^^^^^^^^^^^^^^^^^^^^
                              start_new_session, process_group)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dento\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1548, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                                   # no special security
                                   ^^^^^^^^^^^^^^^^^^^^^
          ...<4 lines>...
                                   cwd,
                                   ^^^^
                                   startupinfo)
                                   ^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

```

Issue seems to be here: https://github.com/rucio/rucio/blob/f259ef5f259c150092755d116f543127e724255b/setuputil.py#L103-L125

### Steps to reproduce

https://rucio.cern.ch/documentation/user/setting_up_the_rucio_client/

**Comment by bari12** [comment]
@Geogouz can you confirm that this is fixed in 39.0? (Pyproject should have fixed this)

**Comment by Geogouz** [comment]
Indeed, with `pip install "rucio-clients==39.0.0" --no-binary rucio-clients --no-cache-dir -v` I'm getting on windows: `Successfully installed rucio-clients-39.0.0`

Also, from what I see, the installation using windows Pycharm's package manager woks too (nice).

<img width="1978" height="1462" alt="Image" src="https://github.com/user-attachments/assets/b102ca3e-6ede-46f8-8d4c-e45612d8829d" />
