### ISSUE TITLE
Importing a schema from a policy package with a `lfn2pfn` algorithm results in circular imports due to module-level logic

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#7165]
### Description

This occurs when resetting the database for tests. See this traceback for the full log:

```
Traceback (most recent call last):
  File "/opt/rucio/tools/reset_database.py", line 25, in <module>
    from rucio.db.sqla.util import build_database, create_base_vo, create_root_account, destroy_database, drop_everything  # noqa: E402
  File "/opt/venv/lib64/python3.9/site-packages/rucio/db/sqla/util.py", line 36, in <module>
    from rucio.common.schema import get_schema_value
  File "/opt/venv/lib64/python3.9/site-packages/rucio/common/schema/__init__.py", line 49, in <module>
    check_policy_package_version(POLICY)
  File "/opt/venv/lib64/python3.9/site-packages/rucio/common/plugins.py", line 42, in check_policy_package_version
    supported_version = _get_supported_version_from_policy_package(package)
  File "/opt/venv/lib64/python3.9/site-packages/rucio/common/plugins.py", line 57, in _get_supported_version_from_policy_package
    module = importlib.import_module(package)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/venv/lib64/python3.9/site-packages/belleii_rucio_policy_package/__init__.py", line 3, in <module>
    from belleii_rucio_policy_package.lfn2pfn import BelleIIRSEDeterministicTranslation
  File "/opt/venv/lib64/python3.9/site-packages/belleii_rucio_policy_package/lfn2pfn.py", line 1, in <module>
    import rucio.rse.translation
  File "/opt/venv/lib64/python3.9/site-packages/rucio/rse/__init__.py", line 18, in <module>
    from rucio.rse import rsemanager
  File "/opt/venv/lib64/python3.9/site-packages/rucio/rse/rsemanager.py", line 22, in <module>
    from rucio.common import constants, exception, types, utils
  File "/opt/venv/lib64/python3.9/site-packages/rucio/common/constants.py", line 45, in <module>
    if config_get_bool('transfers', 'srm_https_compatibility', raise_exception=False, default=False):
  File "/opt/venv/lib64/python3.9/site-packages/rucio/common/config.py", line 517, in config_get_bool
    return config_get(
  File "/opt/venv/lib64/python3.9/site-packages/rucio/common/config.py", line 205, in config_get
    return __config_get_table(section=section, option=option, raise_exception=raise_exception,
  File "/opt/venv/lib64/python3.9/site-packages/rucio/common/config.py", line 661, in __config_get_table
    from rucio.core.config import get as core_config_get
  File "/opt/venv/lib64/python3.9/site-packages/rucio/core/config.py", line 22, in <module>
    from rucio.db.sqla.models import Config
  File "/opt/venv/lib64/python3.9/site-packages/rucio/db/sqla/models.py", line 319, in <module>
    class Account(BASE, ModelBase):
  File "/opt/venv/lib64/python3.9/site-packages/rucio/db/sqla/models.py", line 322, in Account
    account: Mapped[InternalAccount] = mapped_column(InternalAccountString(common_schema.get_schema_value('ACCOUNT_LENGTH')))
AttributeError: partially initialized module 'rucio.common.schema' has no attribute 'get_schema_value' (most likely due to a circular import)
Failed to reset the database!
```

This issue occurs due to this module-level logic:

https://github.com/rucio/rucio/blob/3f8b419609f7b776cff61267fcf6323054bf260c/lib/rucio/common/schema/__init__.py#L37-L69

What happens is:
1. `get_schema_value` is imported when resetting the database
2. if not `multivo`, the policy package specified in the config is imported
3. The policy package's `lfn2pfn` algorithm has to subclass `RSEDeterministicTranslation`, which results in having to eventually import `get_schema_value`

### Steps to reproduce

1. import schema from policy package

**Comment by rdimaio** [comment]
A simple fix is to move the algorithm imports in the policy package so that they are under `get_algorithms` (https://rucio.github.io/documentation/operator/policy_packages/#creating-a-policy-package) to avoid importing them before the policy schema is imported. The alternative would be to keep the permission and schema in a separate module than the algorithms, and handling them separately, but I think implementing this workaround is fine for this purpose.

I will update the docs to reflect this

**Comment by rdimaio** [comment]
PR to docs: https://github.com/rucio/documentation/pull/389
