### ISSUE TITLE
declare-bad of LFN fails if primary protocols not same

### ISSUE THREAD

**Issue by rodwalker** [rucio/rucio#7180]
### Description

If the primary protocols are not the same(a mix of davs and root) for all replicas then declaring the LFC bad does not work. I get the same result by listing the replicas separately. It means the internal replic resolution needs to set davs as the preffered protocol.

Cheers,
Rod.

### Steps to reproduce

Not going to work now since I declared with 4 explicit replicas now (with same protocol).
$ rucio-admin replicas declare-bad --reason="Corrupt ATEAM-1034"  data22_13p6TeV:DRAW_EGZ.41921624._001479.1
Provided type is considered invalid.
Details: The PFNs specified must have the same protocol
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/34.1.0/bin/rucio-admin", line 110, in new_funct
    return function(*args, **kwargs)
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/34.1.0/bin/rucio-admin", line 1128, in declare_bad_file_replicas
    non_declared = client.declare_bad_file_replicas(bad_files_pfns, args.reason)
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/34.1.0/lib/python3.9/site-packages/rucio/client/replicaclient.py", line 70, in declare_bad_file_replicas
    raise exc_cls(exc_msg)
rucio.common.exception.InvalidType: Provided type is considered invalid.
Details: The PFNs specified must have the same protocol

**Comment by bari12** [comment]
@ericvaandering 
I am trying to unwind this issue a little bit. Some years ago you added the declaration of bad replicas via dids. But the existing [method](https://github.com/rucio/rucio/blob/dfcd980f4f10720af38ea1570a6015b2478a5408/lib/rucio/client/replicaclient.py#L57C29-L57C30) already supported that. What was the reason for not using this? I am trying to understand the code but it's not clear to me.
