### ISSUE TITLE
rucio-judge-cleaner traceback against postgres

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#722]
Motivation
----------

```# /bin/rucio-judge-cleaner 
Traceback (most recent call last):
  File "/bin/rucio-judge-cleaner", line 30, in <module>
    run(once=args.run_once, threads=args.threads)
  File "/usr/lib/python2.7/site-packages/rucio/daemons/judge/cleaner.py", line 143, in run
    if db_time - client_time > max_offset or client_time - db_time > max_offset:
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime' ```

**Comment by bari12** [comment]
Ok it seems in certain versions of postgres only a date, instead of a datatime is returned when querying the db. With a date object this check becomes quite useless. I will disable it in case a date is returned.
