### ISSUE TITLE
The ‘typing_extensions’ module is not included in the dependencies

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#7238]
### Description

As title suggests.

### Steps to reproduce

```console
$ python3 -m venv rucio
$ source rucio/bin/activate
$ pip3 install --quiet rucio-clients

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
$ :  # Populate the commands directory from the repository
$ rucio whoami
Traceback (most recent call last):
  File "/var/home/dchristidis/rucio/bin/rucio", line 20, in <module>
    from rucio.client.commands.bin_legacy.rucio import main as main_legacy
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/__init__.py", line 14, in <module>
    from rucio.client.commands.account import Account  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/account.py", line 17, in <module>
    from rucio.client.commands.bin_legacy.rucio import list_account_usage
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/bin_legacy/rucio.py", line 42, in <module>
    from rucio.client.commands.utils import exception_handler, get_client, setup_gfal2_logger, signal_handler
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/utils.py", line 25, in <module>
    from typing_extensions import NotRequired, TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```

### Rucio Version

`36.0.0`

**Comment by rdimaio** [comment]
This is the first usage of `typing_extensions` within the client; this module is listed as a secondary dependency for server and dev, but not for client.  I'll add it to `client` as well

**Comment by dchristidis** [comment]
```console
$ pip show rucio-clients
Name: rucio-clients
Version: 36.0.0.post1
Summary: Rucio Client Lite Package
Home-page: https://rucio.cern.ch/
Author: Rucio
Author-email: rucio-dev@cern.ch
License: Apache License, Version 2.0
Location: /var/home/dchristidis/rucio/lib64/python3.13/site-packages
Requires: dogpile-cache, jsonschema, packaging, requests, rich, tabulate, urllib3
Required-by:
```

**Comment by bari12** [comment]
During the sdist build it showed up like this:
```
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (packaging, setuptools, wheel)
* Getting build dependencies for sdist...
requirement found install_requires requests>=2.32.2
requirement found install_requires urllib3>=1.26.18
requirement found install_requires dogpile-cache>=1.2.2
requirement found install_requires tabulate>=0.9.0
requirement found install_requires jsonschema>=4.20.0
requirement found install_requires packaging>=24.1
requirement found install_requires rich>=13.7.1
requirement unused typing-extensions>=4.12.2 (from typing-extensions)
```
🤔

**Comment by rdimaio** [comment]
Seems like it's missing from the client `requires`

**Comment by rdimaio** [comment]
I believe this should fix it: https://github.com/rucio/rucio/pull/7272
This one might not be necessary: https://github.com/rucio/rucio/pull/7271 but it might still be worth adding
