### ISSUE TITLE
New CLI: argparse.ArgumentError

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#7239]
### Description

As title suggests.

### Steps to reproduce

```console
$ python3 -m venv rucio
$ source rucio/bin/activate
$ pip3 install --quiet rucio-clients

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
$ :  # Populate the commands directory from the repository
$ pip3 install --quiet typing_extensions

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
$ rucio whoami
Traceback (most recent call last):
  File "/var/home/dchristidis/rucio/bin/rucio", line 96, in <module>
    main()
    ~~~~^^
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/command.py", line 226, in main
    parser_object = Commands._add_parsers()
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/command.py", line 74, in _add_parsers
    command(None, None, None, None, None).parser(subparsers)  # type: ignore
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/command.py", line 211, in parser
    command_parser = subparser.add_parser("test-server", description="Test client against the server", formatter_class=argparse.RawDescriptionHelpFormatter)
  File "/usr/lib64/python3.13/argparse.py", line 1193, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument command: conflicting subparser: test-server
```

### Rucio Version

`36.0.0`

**Comment by rdimaio** [comment]
We have two instances of `subparser.add_parser("test-server"..`, that seems to be the issue

**Comment by voetberg** [comment]
Now why wasn't this caught by the tests 🤔

**Comment by dchristidis** [comment]
With `36.0.0post1`, having applied workarounds for #7238 and #7270, the issue persists:

```console
$ rucio whoami
Traceback (most recent call last):
  File "/var/home/dchristidis/rucio/bin/rucio", line 96, in <module>
    main()
    ~~~~^^
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/command.py", line 227, in main
    parser_object = Commands._add_parsers()
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/command.py", line 74, in _add_parsers
    command(None, None, None, None, None).parser(subparsers)  # type: ignore
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/command.py", line 212, in parser
    command_parser = subparser.add_parser("test-server", description="Test client against the server", formatter_class=argparse.RawDescriptionHelpFormatter)
  File "/usr/lib64/python3.13/argparse.py", line 1193, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument command: conflicting subparser: test-server
```

**Comment by voetberg** [comment]
I'm trying to figure out why this happens with the packaged release and not an install from source, really a head scratcher for me. What version of `argparse` do you have in this venv?

**Comment by dchristidis** [comment]
```console
$ python3 --version
Python 3.13.0
```
