### ISSUE TITLE
New CLI: AttributeError for X.509 authentication

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#7242]
### Description

~~Seems like the client requires some command-line arguments which should be optional.~~

### Steps to reproduce

```console
$ python3 -m venv rucio
$ source rucio/bin/activate
$ pip3 install --quiet rucio-clients

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
$ :  # Populate the commands directory from the repository
$ pip3 install --quiet typing_extensions

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
$ :  # Edit the files to address issue #7239
$ rucio whoami
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /var/home/dchristidis/rucio/bin/rucio:96 in <module>                                                                 │
│                                                                                                                      │
│    93 │   is_legacy = '--legacy' in sys.argv                                                                         │
│    94 │                                                                                                              │
│    95 │   if (first_command in commands) and not is_legacy:                                                          │
│ ❱  96 │   │   main()                                                                                                 │
│    97 │                                                                                                              │
│    98 │   elif is_legacy:                                                                                            │
│    99 │   │   warning = make_warning()                                                                               │
│                                                                                                                      │
│ /var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/command.py:244 in main              │
│                                                                                                                      │
│   241 │   else:                                                                                                      │
│   242 │   │   logger = setup_logger(module_name=__name__, logger_name="user", verbose=args.ver                       │
│   243 │                                                                                                              │
│ ❱ 244 │   client = get_client(args, logger)                                                                          │
│   245 │   signal.signal(signal.SIGINT, lambda sig, frame: signal_handler(sig, frame, logger))                        │
│   246 │                                                                                                              │
│   247 │   Commands(logger, client, args, console, spinner)()                                                         │
│                                                                                                                      │
│ /var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/utils.py:195 in get_client          │
│                                                                                                                      │
│   192 │   │   │   "oidc_password": args.oidc_password,                                                               │
│   193 │   │   }                                                                                                      │
│   194 │   elif auth_type == "x509":                                                                                  │
│ ❱ 195 │   │   creds = {"client_cert": args.certificate, "client_key": args.client_key}                               │
│   196 │   else:                                                                                                      │
│   197 │   │   creds = None                                                                                           │
│   198                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'client_key'
```

10 points for the Rich output!

### Rucio Version

`36.0.0`

**Comment by dchristidis** [comment]
Can’t pass a `--client_key` command-line parameter either.

**Comment by dchristidis** [comment]
~~Running the client with the old command structure works fine.~~

Only some of them. :D

**Comment by voetberg** [comment]
Looks when the client-key option was inconsistent between `rucio` and `rucio-admin` (view https://github.com/rucio/rucio/commit/d58adca2bf1f592bd4586f2de246df50e6bc2012 as the last pre-new-cli commit), so commands from rucio-admin will break when using x509 via cli kwarg login.... Heck of a round-about way to find that bug.

**Comment by dchristidis** [comment]
Still happening with some commands in `36.0.0post1`. For example:

```console
$ rucio-admin rse info CERN-PROD_DATADISK

WARNING: This method is being deprecated.
Please replace your command with `rucio rse info`.

Traceback (most recent call last):
  File "/var/home/dchristidis/rucio/bin/rucio-admin", line 89, in <module>
    main_legacy()
    ~~~~~~~~~~~^^
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/bin_legacy/rucio_admin.py", line 2470, in main
    client = get_client(args, logger)
  File "/var/home/dchristidis/rucio/lib64/python3.13/site-packages/rucio/client/commands/utils.py", line 195, in get_client
    creds = {"client_cert": args.certificate, "client_key": args.client_key}
                                                            ^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'client_key'
```
