### ISSUE TITLE
Injector needs to catch InsufficientAccountLimit

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#76]
```
2017-10-05 09:11:53,730 9234 CRITICAL Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/rucio/daemons/judge/injector.py", line 87, in rule_injector inject_rule(rule_id=rule_id) File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 349, in new_funct result = function(args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/rule.py", line 630, in inject_rule
    session=session)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 365, in new_funct
    result = function(args, kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/rule.py", line 2674, in __create_locks_replicas_transfers
    session=session)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 365, in new_funct
    result = function(*args, kwargs) File "/usr/lib/python2.7/site-packages/rucio/core/rule_grouping.py", line 88, in apply_rule_grouping session=session) File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 365, in new_funct result = function(args, *kwargs) File "/usr/lib/python2.7/site-packages/rucio/core/rule_grouping.py", line 429, in __apply_rule_to_files_dataset_grouping prioritize_order_over_weight=True) File "/usr/lib/python2.7/site-packages/rucio/core/rse_selector.py", line 115, in select_rse raise InsufficientAccountLimit('There is insufficient quota on any of the target RSE\'s to fullfill the operation.') InsufficientAccountLimit: There is not enough quota left to fulfil the operation. Details: There is insufficient quota on any of the target RSE's to fullfill the operation.
```

_Migrated from JIRA [RUCIO-2827](https://its.cern.ch/jira/browse/RUCIO-2827)_

**Comment by bari12** [comment]
@cserf I wonder what the correct behaviour is there. I cannot just catch it and ignore it, because then the rule will stay in the queue probably forever. On the other hand, if I just remove the rule than the user will never know that it was deleted, due to it's async nature. Maybe the right thing is to put it to SUSPENDED. Opinions?

**Comment by cserf** [comment]
The behaviour should be that the rule is not replicated to the new RSE and kept at the current RSE

**Comment by bari12** [comment]
But there is no current RSE?

**Comment by cserf** [comment]
Ahhh... sorry. I thought it was BB8 :-) (didn't recover from my jet-lag fro Gex :p )
SUSPENDED would be the right thing to do
