### ISSUE TITLE
Unhandled exception in conveyor submitter

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#961]
Motivation
----------
Traceback :
```
2018-03-20 15:36:45,244 10981   ERROR   0:1 Failed to prepare requests ['37b310899cba4e7caaa263ccd3515403', '62ade923b2734244b7edc335d4495a78', '6e4fd6f2bea64f4c9808d2ec75e77b67'] state to SUBMITTING(Will not submit jobs but return directly) with error: Traceback (most r
ecent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/conveyor/common.py", line 64, in submit_transfer
    transfer_core.prepare_sources_for_transfers(xfers_ret)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 347, in new_funct
    result = function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/core/transfer.py", line 104, in prepare_sources_for_transfers
    raise RucioException("Failed to prepare transfer: request %s does not exist or is not in queued state" % (request_id))
RucioException: An unknown exception occurred.
Details: Failed to prepare transfer: request 37b310899cba4e7caaa263ccd3515403 does not exist or is not in queued state
```

**Comment by cserf** [comment]
Additional one in the poller :
```
2018-05-23 16:57:18,097 11839   ERROR   Failed to query FTS info: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/conveyor/poller.py", line 231, in poll_transfers
    resps = transfer_core.bulk_query_transfers(external_host, xfers, 'fts3', timeout)
  File "/usr/lib/python2.7/site-packages/rucio/core/transfer.py", line 288, in bulk_query_transfers
    fts_resps = FTS3Transfertool(external_host=request_host).bulk_query(transfer_ids=transfer_ids, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/rucio/transfertool/fts3.py", line 347, in bulk_query
    raise Exception("Failed to parse the job response: %s, error: %s" % (str(jobs), str(error)))
Exception: Failed to parse the job response: <Response [200]>, error: Expecting value: line 2 column 5 (char 14880)
```

**Comment by cserf** [comment]
For the first one, `RequestNotFound` should be raised instead of generic `RucioException` in transfer.py and the exception should be caught in common.py
The second one should catch `JSONDecodeError`
