### ISSUE TITLE
docker-compose requires logconfig 

### ISSUE THREAD

**Issue by brucellino** [rucio/rucio#999]
Motivation
----------

After cloning the repo, I do a 
`pip install -r requirements.readthedocs.txt` which installs the dependencies :tada: 
However 

```
docker-compose etc/docker/dev/docker-compose.yml
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from ..bundle import get_image_digests
  File "/usr/lib/python2.7/dist-packages/compose/bundle.py", line 14, in <module>
    from .service import format_environment
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 13, in <module>
    from docker.utils import LogConfig
ImportError: cannot import name LogConfig
```
I propose to add `logconfig>0.4` to the requirements.

Modification
------------

**Comment by brucellino** [comment]
After some investigation, it looks like this is actually a docker-compose issue on my dev environment.
See https://github.com/docker/compose/issues/1567#issuecomment-307149406

**Comment by brucellino** [comment]
After _further_ investigation, it seems that adding the correct docker-py version to the virtualenv solves the problem.

**Comment by mlassnig** [comment]
Thanks Bruce. Should we expand this on in our documentation?

**Comment by brucellino** [comment]
Hi @mlassnig I'm working on a PR... just checking a few things :smile:

**Comment by mlassnig** [comment]
Cool, thanks ;-)
